-- Three standalone Polish articles (no Czech original), category Cestování/Podróże. Inserted UNPUBLISHED on 28. 9. 2026;
-- Pavla publishes them (published = true) after approval. Images: public/images/clanky/<slug>/.

insert into public.articles (lang, translation_of, slug, title, perex, content, meta_title, meta_description, focus_keyword, category_id, author_id, image_url, og_image, published)
values ('pl', null, $pl$tivoli-kopenhaga$pl$, $pl$Tivoli w Kopenhadze: kiedy jest otwarte i ile kosztuje wstęp (2026/2027)$pl$, $pl$Lądujesz w Kopenhadze w listopadzie albo w grudniu i nie wiesz, czy Tivoli w ogóle działa. Sprawdź dokładny kalendarz otwarcia na sezon 2026/2027, ceny biletów na Halloween i święta oraz to, czy Ride Pass w Twoim przypadku się opłaci.$pl$, $pl$<p>Ogrody Tivoli nie są otwarte przez cały rok, a&nbsp;terminy przerw łatwo przeoczyć, choć dla kogoś z&nbsp;konkretną datą lotu są ważniejsze niż lista atrakcji.</p>
<p>Ceny i&nbsp;daty sprawdzone 28 września 2026 na tivoli.dk i&nbsp;shop.tivoli.dk. Ceny na rok 2027, łącznie z&nbsp;godzinami otwarcia wiosną i&nbsp;latem, nie są jeszcze opublikowane.</p>
<p><em>Zdjęcie tytułowe: Główne wejście od Vesterbrogade. Zdjęcie archiwalne, 2016. Fot. <a href="https://commons.wikimedia.org/wiki/File:I11_444_Tivoli,_Haupteingang.jpg">Falk2</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>. Pomniejszone i przekonwertowane do formatu WebP.</em></p>
<h2>Kiedy Tivoli jest otwarte, a&nbsp;kiedy zamknięte (2026/2027)</h2>
<p>Zimowego sezonu tu nie ma: „Zima w&nbsp;Tivoli” ruszyła w&nbsp;2018 roku, w&nbsp;pandemii ją wstrzymano i&nbsp;od tamtej pory zimą park otwiera się tylko na święta.</p>
<p>Kalendarz na najbliższe miesiące wygląda tak:</p>
<ul><li><strong>Lato 2026</strong> skończyło się w&nbsp;niedzielę 20 września (ostatni dzień 11:00–22:00).</li><li><strong>Zamknięte:</strong> 21 września – 1 października 2026.</li><li><strong>Halloween w&nbsp;Tivoli:</strong> 2 października – 1 listopada 2026.</li><li><strong>Zamknięte:</strong> 2–12 listopada 2026.</li><li><strong>Święta (Jul i&nbsp;Tivoli):</strong> 13 listopada 2026 – 3 stycznia 2027, z&nbsp;wyjątkiem 24 grudnia, kiedy park jest zamknięty.</li><li><strong>Zamknięte:</strong> 4 stycznia – 18 marca 2027.</li><li><strong>Wielkanoc 2027:</strong> 19–29 marca.</li><li><strong>Lato 2027:</strong> 30 marca – 26 września.</li></ul>
<p>Jeśli więc przylatujesz między 2 a&nbsp;12 listopada, masz pecha: park otwiera się dopiero 13 listopada. Za to od tego dnia do 3 stycznia Tivoli działa niemal bez przerwy, poza 24 grudnia.</p>
<p>Godziny otwarcia w&nbsp;sezonie świątecznym i&nbsp;halloweenowym są podobne: w&nbsp;zwykłe dni 11:00–22:00, w&nbsp;piątki i&nbsp;soboty do 23:00. Wyjątki: 24 grudnia zamknięte, 31 grudnia do północy.</p>
<figure><img src="https://kastrup.cz/images/clanky/tivoli-kopenhaga/rutschebanen-snieg-1500.webp" alt="Sztuczna góra kolejki Rutschebanen w Tivoli przykryta śniegiem" loading="lazy"><figcaption>Góra kolejki Rutschebanen widziana od ulicy, styczeń 2026. Fot. <a href="https://commons.wikimedia.org/wiki/File:Sne_p%C3%A5_Rutschebanen_i_Tivoli.jpg">Leif Jørgensen</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>. Pomniejszone i przekonwertowane do formatu WebP.</figcaption></figure>
<h2>Ceny biletów 2026/2027</h2>
<p>Tivoli nie ma jednego cennika na cały sezon: cena zależy od konkretnego dnia, część dni jest „tańsza”, część „droższa”. Sprawdź w&nbsp;kalendarzu na stronie sklepu, do której grupy należy Twoja data, zanim kupisz bilet.</p>
<h3>Ceny na Halloween 2026 (2 października – 1 listopada)</h3>
<p><strong>Dni tańsze:</strong> 2, 5–9, 19–23, 26–30 października. <strong>Dni droższe:</strong> 3, 4, 10–18, 24, 25, 31 października; 1 listopada.</p>
<ul><li>Wstęp, osoba od 8 lat: <strong>200 / 220&nbsp;DKK</strong></li><li>Wstęp, dziecko 3–7 lat: <strong>100 / 110&nbsp;DKK</strong></li><li>Ride Pass, od 8 lat: <strong>269 / 289&nbsp;DKK</strong></li><li>Ride Pass, dziecko 1–7 lat: <strong>134 / 144&nbsp;DKK</strong></li><li>Pakiet wstęp + Ride Pass, od 8 lat: <strong>449 / 489&nbsp;DKK</strong></li></ul>
<p>Domy strachów (Villa Vendetta i&nbsp;The Haunted House razem, jako „Scary House Combo”) nie są objęte Ride Passem. Zestaw kosztuje 150&nbsp;DKK zamiast 190&nbsp;DKK, wstęp od 12 lat.</p>
<figure><img src="https://kastrup.cz/images/clanky/tivoli-kopenhaga/halloween-dynie-1500.webp" alt="Dynie i dekoracje halloweenowe w Ogrodach Tivoli" loading="lazy"><figcaption>Halloween w&nbsp;Tivoli. Zdjęcie archiwalne, 2018. Fot. <a href="https://commons.wikimedia.org/wiki/File:20181030_Tivoli_Halloween_Gr%C3%A6skar_8527_(31774728038).jpg">News Oresund</a>, <a href="https://creativecommons.org/licenses/by/2.0">CC BY 2.0</a>. Pomniejszone i przekonwertowane do formatu WebP.</figcaption></figure>
<h3>Ceny na Boże Narodzenie 2026 (13 listopada – 3 stycznia)</h3>
<p><strong>Dni tańsze:</strong> 13, 16–20, 23–27, 30 listopada; 1–4, 7–11, 28–31 grudnia 2026; 1 stycznia 2027. <strong>Dni droższe:</strong> 14, 15, 21, 22, 28, 29 listopada; 5, 6, 12–23, 25–27 grudnia 2026; 2–3 stycznia 2027.</p>
<p>Ceny za osobę (DKK, dzień tańszy / droższy):</p>
<ul><li>Wstęp, osoba od 8 lat: <strong>210 / 230</strong></li><li>Wstęp, dziecko 3–7 lat: <strong>105 / 115</strong></li><li>Ride Pass (nielimitowane przejazdy), od 8 lat: <strong>199 / 219</strong></li><li>Ride Pass, dziecko 1–7 lat: <strong>99 / 109</strong></li><li>Pakiet wstęp + Ride Pass, od 8 lat: <strong>389 / 429</strong></li><li>Pakiet wstęp + Ride Pass, dziecko 3–7 lat: <strong>194 / 214</strong></li></ul>
<p>Różnica między dniami to zwykle 20&nbsp;DKK na bilecie wstępu dla osoby od 8 lat (10&nbsp;DKK u&nbsp;dziecka, 40&nbsp;DKK w&nbsp;pakiecie).</p>
<p>Dzieci do 3. roku życia wchodzą za darmo; jedna dorosła osoba może wprowadzić bezpłatnie najwyżej czworo takich dzieci. Dzieci poniżej 1. roku życia nie potrzebują Ride Passu, jeśli towarzyszy im płacący opiekun w&nbsp;wieku 14+.</p>
<figure><img src="https://kastrup.cz/images/clanky/tivoli-kopenhaga/jarmark-swiateczny-1500.webp" alt="Świąteczne stragany z lampkami w Ogrodach Tivoli o zmierzchu" loading="lazy"><figcaption>Stragany w&nbsp;sezonie świątecznym. Zdjęcie archiwalne, 2015. Fot. <a href="https://commons.wikimedia.org/wiki/File:Christmas_market_at_Tivoli_(23733451596).jpg">Susanne Nilsson</a>, <a href="https://creativecommons.org/licenses/by-sa/2.0">CC BY-SA 2.0</a>. Pomniejszone i przekonwertowane do formatu WebP.</figcaption></figure>
<h3>Pojedyncze przejazdy, zakup biletów i&nbsp;karnet roczny</h3>
<p>Pojedynczy przejazd bez Ride Passu kosztuje 65&nbsp;DKK (np. Rutschebanen, The Flying Trunk) albo 95&nbsp;DKK przy większych atrakcjach, takich jak Dæmonen, Himmelskibet czy Det Gyldne Tårn. Atrakcje dla najmłodszych są tańsze: The Little Dragon i&nbsp;The Music Carousel kosztują 45&nbsp;DKK za przejazd, The Witches Carousel i&nbsp;The Little Ghost Train 55&nbsp;DKK.</p>
<p>Bilety kupisz na tivoli.dk, w&nbsp;aplikacji Tivoli, w&nbsp;Service Center przy parku albo w&nbsp;jednym z&nbsp;około 30 automatów rozstawionych po ogrodach. Są przypisane do konkretnej daty i&nbsp;nie podlegają zwrotowi. Datę da się zmienić, ale tylko raz i&nbsp;tylko osobiście w&nbsp;kasie w&nbsp;dniu nowej wizyty, w&nbsp;ciągu 14 dni od pierwotnego terminu i&nbsp;w&nbsp;tym samym roku kalendarzowym; różnica na korzyść tańszego biletu nie wraca.</p>
<p>Jeśli wracasz do Tivoli częściej, opłaca się roczny Tivoli Pass: od 449&nbsp;DKK jako subskrypcja albo od 529&nbsp;DKK jako jednorazowy zakup na 12 miesięcy. Karnet daje wstęp we wszystkich sezonach, ale nie obejmuje atrakcji.</p>
<h2>Czy opłaca się Ride Pass?</h2>
<p>Policzmy to na cenach z&nbsp;sezonu świątecznego.</p>
<p>Ride Pass dla dorosłego w&nbsp;tańszy dzień kosztuje 199&nbsp;DKK. Jeśli jeździsz tylko na tańszych atrakcjach po 65&nbsp;DKK, potrzebujesz czterech przejazdów, żeby się to opłaciło: 4 × 65 = 260&nbsp;DKK, czyli więcej niż cena Ride Passu. Przy trzech przejazdach (195&nbsp;DKK) Ride Pass jeszcze się nie zwraca.</p>
<p>Jeśli wybierasz droższe atrakcje po 95&nbsp;DKK, granica opłacalności spada do trzech przejazdów: 3 × 95 = 285&nbsp;DKK. Dwa przejazdy (190&nbsp;DKK) wciąż wychodzą taniej niż sam Ride Pass.</p>
<p>Warto też porównać pakiet wstęp + Ride Pass (389&nbsp;DKK w&nbsp;dzień tańszy) z&nbsp;zakupem obu biletów osobno (210 + 199 = 409&nbsp;DKK). Pakiet wychodzi o&nbsp;20&nbsp;DKK taniej; właśnie 409&nbsp;DKK widać w&nbsp;sklepie jako cenę przekreśloną.</p>
<p>Dla dziecka w&nbsp;wieku 1–7 lat Ride Pass kosztuje w&nbsp;dzień tańszy 99&nbsp;DKK. Dziecięce atrakcje są tańsze niż te dla dorosłych: The Little Dragon i&nbsp;The Music Carousel kosztują 45&nbsp;DKK za przejazd, The Witches Carousel i&nbsp;The Little Ghost Train 55&nbsp;DKK. Przy samych przejazdach po 45&nbsp;DKK próg opłacalności to trzy przejazdy (3 × 45 = 135&nbsp;DKK), przy 55&nbsp;DKK wystarczą dwa (2 × 55 = 110&nbsp;DKK).</p>
<h2>Copenhagen Card w&nbsp;Tivoli</h2>
<p>Copenhagen Card obejmuje <strong>wstęp</strong> do Tivoli: jedna wizyta na kartę, z&nbsp;możliwością powrotu tego samego dnia po odbiciu pieczątki. Nie obejmuje jednak <strong>atrakcji</strong>. Karta daje prawo do zniżkowego Ride Passu, cenę zobaczysz po zalogowaniu numerem karty w&nbsp;sklepie podlinkowanym na stronie Copenhagen Card. Działają zarówno warianty Discover, jak i&nbsp;Hop.</p>
<p>W&nbsp;wybrane piątki, gdy w&nbsp;Tivoli odbywa się letni cykl koncertów Fredagsrock, obowiązują ograniczenia rezerwacji i&nbsp;po wyjściu nie da się tego dnia wrócić. Fredagsrock gra tylko latem, więc wizyty w&nbsp;Halloween i&nbsp;w&nbsp;święta to nie dotyczy.</p>
<h2>Limity wzrostu na atrakcjach</h2>
<p>Jeśli jedziesz z&nbsp;małymi dziećmi, sprawdź te liczby przed zakupem biletów, a&nbsp;nie po nim:</p>
<ul><li><strong>Rutschebanen</strong> (drewniana kolejka górska z&nbsp;1914 roku): od 120&nbsp;cm, bez limitu wzrostu z&nbsp;płacącym opiekunem 14+.</li><li><strong>The Flying Trunk</strong> (przejażdżka przez baśnie Andersena): od 130&nbsp;cm, bez limitu z&nbsp;opiekunem 14+.</li><li><strong>Dæmonen</strong>: od 132&nbsp;cm.</li><li><strong>Det Gyldne Tårn</strong> (swobodny spadek z&nbsp;63 metrów): od 132&nbsp;cm.</li><li><strong>Himmelskibet</strong> (karuzela na wysokości 80 metrów): od 140&nbsp;cm, a&nbsp;w&nbsp;przedziale 120–140&nbsp;cm tylko z&nbsp;opiekunem 14+.</li></ul>
<p>Rutschebanen to jedna z&nbsp;najstarszych wciąż działających drewnianych kolejek górskich na świecie i&nbsp;jedna z&nbsp;zaledwie siedmiu, w&nbsp;których w&nbsp;każdym pociągu jedzie hamulcowy.</p>
<figure><img src="https://kastrup.cz/images/clanky/tivoli-kopenhaga/himmelskibet-1500.webp" alt="Karuzela Himmelskibet w Tivoli widziana z dołu na tle nieba" loading="lazy"><figcaption>Himmelskibet. Zdjęcie archiwalne, 2015. Fot. <a href="https://commons.wikimedia.org/wiki/File:Himmelskibet_Tivoli.jpg">AMPendrill</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>. Pomniejszone i przekonwertowane do formatu WebP.</figcaption></figure>
<h2>Jak dojechać z&nbsp;lotniska Kastrup i&nbsp;z&nbsp;dworca głównego</h2>
<p>Główne wejście do Tivoli jest przy <strong>Vesterbrogade 3</strong>, drugie prowadzi od strony dworca głównego, z&nbsp;ulicy Bernstorffsgade; działa od 1912 roku, rok po otwarciu nowego budynku dworca. Poza sezonem tym drugim wejściem, przy H.C. Andersens Boulevard 26, chodzi się na przedstawienia w&nbsp;Glassalen i&nbsp;sali koncertowej; niezależnie od sezonu w&nbsp;ogrodach cały rok działa tam też Tivoli Food Hall, z&nbsp;osobnym wejściem od ulicy.</p>
<p>Dworzec główny København H, stacja Vesterport i&nbsp;plac Rådhuspladsen są niecałe pięć minut pieszo od Tivoli. Ze stacji metra København H (linie M3 i&nbsp;M4) dojdziesz do Tivoli w&nbsp;około 2 minuty. Z&nbsp;lotniska Kastrup dojedziesz do København H pociągiem (13 minut) albo autobusem 5C (35 minut); metro M2 jedzie do centrum, ale nie bezpośrednio na dworzec główny. Szczegóły opisaliśmy w&nbsp;tekście o&nbsp;<a href="/artykul/lotnisko-kopenhaga-dojazd-do-centrum">dojeździe z&nbsp;lotniska do centrum Kopenhagi</a>.</p>
<p>Jeśli dopiero planujesz resztę pobytu, zerknij też do naszego <a href="/kopenhaga">przewodnika po Kopenhadze</a>.</p>
<h2>Co warto wiedzieć przed wizytą</h2>
<p>Własne jedzenie i&nbsp;napoje bezalkoholowe można wnieść do ogrodów. Zjeść je wolno na trawniku przy Open Air Stage, w&nbsp;części ogrodów wzdłuż H.C. Andersens Boulevard i&nbsp;na ławkach. Własny alkohol i&nbsp;szklane butelki są zakazane. Psów, poza psami przewodnikami i&nbsp;asystującymi, też nie wolno wprowadzać.</p>
<p>Szatnie i&nbsp;skrytki są przy głównym wejściu, przy wyjściu obok Ny Carlsberg Glyptotek i&nbsp;pod Dæmonen. Duża skrytka kosztuje 50&nbsp;DKK, największa (Jumbo) 70&nbsp;DKK.</p>
<p>W&nbsp;sezonie świątecznym działają wszystkie atrakcje, choć pojedyncze mogą akurat stanąć do konserwacji, więc jeśli zależy Ci na konkretnej, sprawdź jej stronę na tivoli.dk. Do tego dochodzą świąteczny pociąg (Elf Train) i&nbsp;leśna karuzela (Forest Carousel). Są tysiące lampek, jarmarczne stragany i&nbsp;domek Świętego Mikołaja, czyli wszystko, co Duńczycy wrzucają do jednego worka z&nbsp;napisem <a href="/hygge">hygge</a>. Tivoli chwali się, że CNN umieściło jego jarmark na liście najlepszych świątecznych jarmarków.</p>
<figure><img src="https://kastrup.cz/images/clanky/tivoli-kopenhaga/jezioro-noca-1500.webp" alt="Jezioro w Tivoli nocą z oświetloną japońską wieżą" loading="lazy"><figcaption>Jezioro i&nbsp;japońska wieża w&nbsp;grudniu. Zdjęcie archiwalne, 2014. Fot. <a href="https://commons.wikimedia.org/wiki/File:20141228-MAT_1324.jpg">MattXDA</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>. Pomniejszone i przekonwertowane do formatu WebP.</figcaption></figure>
<p>Na sylwestra Tivoli zapowiada o&nbsp;północy fajerwerki i&nbsp;noworoczne koncerty, a&nbsp;park jest otwarty do 00:00. Czy pokaz wymaga osobnego biletu i&nbsp;skąd najlepiej go oglądać, sprawdź na tivoli.dk bliżej sylwestra.</p>
<p>Jeśli podróżujesz z&nbsp;dziećmi, przyda się też nasz osobny <a href="/artykul/kopenhaga-z-dziecmi">przewodnik po Kopenhadze z&nbsp;dziećmi</a>. W&nbsp;grudniu warto rozłożyć Tivoli i&nbsp;miasto na dwa dni, a&nbsp;nocleg blisko centrum wybierzesz z&nbsp;naszego zestawienia <a href="/noclegi">noclegów w&nbsp;Kopenhadze</a>.</p>
<h2>Czego lepiej uniknąć</h2>
<p>Najczęstsze wpadki:</p>
<ul><li><strong>Przyjazd w&nbsp;dniu, kiedy park jest zamknięty.</strong> Między sezonami bramy są zamknięte po kilkanaście dni (21 września – 1 października, 2–12 listopada).</li><li><strong>Kupno Ride Passu dziecku, które nie sięga wymaganej wysokości.</strong> Ride Pass daje wstęp na atrakcje, ale nie znosi limitów wzrostu: 132&nbsp;cm przy Dæmonen czy Det Gyldne Tårn obowiązują niezależnie od tego, ile kosztował bilet.</li><li><strong>Poleganie na Copenhagen Card jako na przepustce na wszystko.</strong> Karta otwiera bramę Tivoli, ale za każdą przejażdżkę i&nbsp;tak trzeba zapłacić, chyba że dokupisz zniżkowy Ride Pass.</li><li><strong>Planowanie wizyty na 24 grudnia.</strong> W&nbsp;Wigilię Tivoli jest zamknięte, choć przez resztę grudnia działa codziennie.</li></ul>
<h2>FAQ</h2>
<p><strong>Czy Tivoli jest otwarte w&nbsp;listopadzie?</strong> Częściowo. Od 2 do 12 listopada 2026 park jest zamknięty, ale od 13 listopada rusza sezon świąteczny i&nbsp;Tivoli działa codziennie aż do 3 stycznia 2027, z&nbsp;wyjątkiem 24 grudnia. 1 listopada to jeszcze ostatni dzień Halloween.</p>
<p><strong>Ile kosztuje wstęp do Tivoli?</strong> Zależy od sezonu i&nbsp;dnia. Na Halloween 2026 wstęp dla osoby od 8 lat kosztuje 200 lub 220&nbsp;DKK, w&nbsp;sezonie świątecznym 210 lub 230&nbsp;DKK. Dzieci od 3 do 7 lat płacą połowę, a&nbsp;do 3. roku życia wchodzą bezpłatnie.</p>
<p><strong>Czy Copenhagen Card obejmuje atrakcje w&nbsp;Tivoli?</strong> Nie. Karta obejmuje tylko wstęp do ogrodów, z&nbsp;możliwością powrotu tego samego dnia. Za same atrakcje trzeba dopłacić, choć karta daje prawo do zniżkowego Ride Passu.</p>
<p><strong>Czy można wnieść do Tivoli własne jedzenie?</strong> Tak, jedzenie i&nbsp;napoje bezalkoholowe są dozwolone i&nbsp;można je zjeść w&nbsp;wyznaczonych miejscach: na trawniku przy Open Air Stage, w&nbsp;części ogrodów wzdłuż H.C. Andersens Boulevard i&nbsp;na ławkach. Własny alkohol i&nbsp;szklane butelki są zakazane.</p>
<p><strong>Od ilu lat dziecko może jeździć na kolejce górskiej Rutschebanen?</strong> Nie decyduje wiek, tylko wzrost: bez opiekuna od 120&nbsp;cm. Niższe dziecko może jechać z&nbsp;płacącym opiekunem w&nbsp;wieku 14+, wtedy limit wzrostu nie obowiązuje.</p>
<p><strong>Źródła:</strong> tivoli.dk (kalendarz otwarcia, FAQ, regulamin, strony atrakcji, historia Tivoli, strona świąteczna), shop.tivoli.dk (ceny biletów i&nbsp;pakietów), copenhagencard.com (zakres Copenhagen Card), m.dk (stacja metra København H). Ceny i&nbsp;daty sprawdzone 28 września 2026, ceny i&nbsp;godziny na rok 2027 jeszcze nieopublikowane.</p>$pl$, $pl$Tivoli Kopenhaga: godziny otwarcia i ceny | Kastrup.pl$pl$, $pl$Kiedy Tivoli w Kopenhadze jest otwarte, a kiedy zamknięte? Ceny na Halloween i święta 2026, opłacalność Ride Passu i limity wzrostu dla dzieci.$pl$, $pl$Tivoli Kopenhaga$pl$, 'cbf723ca-1307-4ffd-8717-5b673c8643cd', '415c2012-9d88-4267-9b21-63b93ab384ad', $pl$https://kastrup.cz/images/clanky/tivoli-kopenhaga/wejscie-vesterbrogade-1500.webp$pl$, $pl$https://kastrup.cz/images/clanky/tivoli-kopenhaga/wejscie-vesterbrogade-1500.webp$pl$, false)
on conflict (lang, slug) do update set title=excluded.title, perex=excluded.perex, content=excluded.content, meta_title=excluded.meta_title,
  meta_description=excluded.meta_description, focus_keyword=excluded.focus_keyword, image_url=excluded.image_url, og_image=excluded.og_image, updated_at=now()
returning slug, published, length(content) as len, md5(content) as md5;

insert into public.articles (lang, translation_of, slug, title, perex, content, meta_title, meta_description, focus_keyword, category_id, author_id, image_url, og_image, published)
values ('pl', null, $pl$legoland-dania$pl$, $pl$Legoland Dania: ceny, godziny i dojazd z Polski (2026)$pl$, $pl$Legoland w Billund nie jest wycieczką za rogiem. Sprawdź, ile realnie kosztuje bilet online i na bramie, kiedy park w 2026 roku jest otwarty, a kiedy zamknięty, i którą trasą z Polski dojedziesz bez zbędnych opłat za mosty.$pl$, $pl$<p>Twoje dziecko zobaczyło filmik z&nbsp;Legolandu i&nbsp;teraz nie odpuszcza tematu. Ty w&nbsp;tym czasie otwierasz mapę, liczysz kilometry z&nbsp;Polski, potem przeglądasz cennik i&nbsp;zastanawiasz się, czy to się w&nbsp;ogóle spina na jeden długi weekend. Legoland Billund leży w&nbsp;środku Jutlandii, więc to albo od około 650 do ponad 1100&nbsp;km autem przez Niemcy, albo lot na lotnisko, które leży kilka kilometrów od parku.</p>
<p><strong>Ceny i&nbsp;daty sprawdzone 28 września 2026.</strong> Wszystkie kwoty podajemy w&nbsp;koronach duńskich (DKK), bez przeliczania na złote, bo kurs złotego się zmienia.</p>
<h2>Dla kogo jest Legoland Billund</h2>
<p>Park działa od 1968 roku i&nbsp;sam pisze o&nbsp;sobie, że jest odpowiedni dla dzieci w&nbsp;wieku od 3 do 12 lat, ale też jest fajnym miejscem dla rodzin w&nbsp;każdym wieku. To ponad 45 atrakcji, 80 milionów klocków LEGO i&nbsp;11 stref tematycznych. Sercem parku jest Miniland, świat w&nbsp;miniaturze zbudowany z&nbsp;ponad 20 milionów klocków, do którego w&nbsp;2026 roku dołączyła makieta Kopenhagi.</p>
<p>28 września 2026 roku strona parku informowała, że tegoroczna nowość, Minifigure Speedway, jest zamknięta z&nbsp;powodu przerwy technicznej, bez terminu ponownego otwarcia. Jeśli akurat na nią liczysz, sprawdź stan tuż przed wyjazdem.</p>
<p><em>Zdjęcie tytułowe: Wejście do LEGOLAND Billund. Zdjęcie archiwalne, 2013. Fot. <a href="https://commons.wikimedia.org/wiki/File:Legoland_Denmark.JPG">Hans Christian Fog</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>. Pomniejszone i przekonwertowane do formatu WebP.</em></p>
<h2>Kiedy Legoland jest otwarty w&nbsp;2026 (i&nbsp;czego jeszcze nie wiadomo o&nbsp;2027)</h2>
<p>Jesienny kalendarz 2026 roku wygląda tak:</p>
<ul><li>Halloween: 2 października – 1 listopada 2026.</li><li>Wieczorne otwarcie: 10–17 października park jest otwarty do 21, część atrakcji działa do 20.</li><li>Zamknięte w&nbsp;tym czasie: 29–30 września oraz 1, 6–8 i&nbsp;28–29 października (w&nbsp;kalendarzu parku tych dni po prostu nie ma).</li><li>Przerwa między sezonami: 2–27 listopada 2026 park jest zamknięty całkowicie.</li><li>Sezon świąteczny: 28 listopada – 31 grudnia 2026, ale nie codziennie. Otwarte są 28–29 listopada, od piątku do niedzieli 4–6 i&nbsp;11–13 grudnia, potem codziennie 18–23 i&nbsp;27–31 grudnia (31 grudnia krócej, 10–16). Na same święta, 24–26 grudnia, park jest zamknięty.</li></ul>
<figure><img src="https://kastrup.cz/images/clanky/legoland-dania/minifigure-speedway-1500.webp" alt="Kolejka górska Minifigure Speedway w LEGOLAND Billund" loading="lazy"><figcaption>Minifigure Speedway, nowość sezonu 2026 (zdjęcie z&nbsp;kwietnia 2026). Fot. <a href="https://commons.wikimedia.org/wiki/File:Legoland_Billund_-_Minifigure_Speedway_01.jpg">Leif Jørgensen</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>. Pomniejszone i przekonwertowane do formatu WebP.</figcaption></figure>
<p>Godziny otwarcia też się zmieniają: 10–17 na przełomie września i&nbsp;października, 10–18 przez większość października i&nbsp;w&nbsp;okresie świątecznym, 10–21 w&nbsp;tygodniu wieczornego otwarcia. Atrakcje przestają działać godzinę przed zamknięciem bramy, więc ostatnia godzina w&nbsp;parku to już tylko spacer po Minilandzie i&nbsp;sklepy. Park zastrzega sobie prawo do zmiany kalendarza, traktuj więc te daty jako stan na dziś, nie gwarancję.</p>
<p>Początku sezonu 2027 park jeszcze nie ogłosił. W&nbsp;centrum obsługi klienta park pisze wprost, że kalendarz na kolejny rok publikuje dopiero pod koniec roku. W&nbsp;2026 sezon ruszył pod koniec marca, ale wiemy to tylko z&nbsp;lokalnej gazety. To wskazówka, nie termin.</p>
<h2>Ile kosztuje bilet w&nbsp;2026: online kontra brama</h2>
<ul><li>Bilet jednodniowy: online od 349&nbsp;DKK, na bramie 519&nbsp;DKK. Park sam podaje, że online da się zaoszczędzić do 170&nbsp;DKK na osobę.</li><li>Dla rodziny 2+2 to już różnica do 680&nbsp;DKK (4 × 170&nbsp;DKK) tylko za to, że kupisz bilety wcześniej zamiast na bramie – jeśli dzieci mają ukończone 2 lata.</li><li>Bilet dwudniowy: online od 498&nbsp;DKK, na bramie 688&nbsp;DKK. Drugi dzień dokupisz od 149&nbsp;DKK, ale trzeba go wykorzystać w&nbsp;ciągu 6 dni od pierwszej wizyty.</li><li>Bilet dwudniowy da się kupić tylko do 1 listopada włącznie. Czy to znaczy, że na grudzień go nie ma, cennik nie mówi – sprawdź to w&nbsp;koszyku.</li><li>Bilet niedatowany na jeden dzień: online 469&nbsp;DKK, na bramie 519&nbsp;DKK, ważny w&nbsp;dowolnym dniu otwarcia do 1 listopada 2026. Przyda się, jeśli jeszcze nie znasz dokładnej daty wyjazdu.</li><li>Bilet łączony Legoland + LEGO House: online od 649&nbsp;DKK, a&nbsp;według parku osobne bilety kosztują razem 878&nbsp;DKK. Wejście do Legolandu możesz wykorzystać do 6 dni przed wizytą w&nbsp;LEGO House lub po niej. Dla porównania: oba bilety osobno online w&nbsp;najtańszym wariancie (349 + 189&nbsp;DKK) wyjdą od 538&nbsp;DKK, taniej niż kombi – zależy, na jakie ceny akurat trafisz.</li><li>Dzieci poniżej 2 lat wchodzą bezpłatnie. Osobnej ceny dla dzieci cennik nie podaje, więc wygląda na to, że od drugich urodzin wszyscy płacą tyle samo (to nasz wniosek, nie zapis na stronie).</li><li>Bilety online nie podlegają zwrotowi, kupić je może tylko osoba pełnoletnia, a&nbsp;podane ceny zawierają 25-procentowy VAT.</li></ul>
<p>Jeśli myślisz o&nbsp;kilku wizytach w&nbsp;sezonie, park sprzedaje też karnety sezonowe. Karnet AWESOME Season Pass 2027 + rest of 2026 (tak dokładnie nazywa go park) kosztuje 749&nbsp;DKK jako nowy i&nbsp;699&nbsp;DKK przy odnowieniu, obejmuje resztę 2026 roku i&nbsp;cały 2027, w&nbsp;cenie jest bezpłatne parkowanie na zwykłym miejscu. Droższy EXTREME obowiązuje tylko do końca 2026 roku i&nbsp;kosztuje 1199&nbsp;DKK (nowy albo odnowienie), zawiera kartę parkingową 2026 wartą 220&nbsp;DKK. Park chwali się, że ma ponad 200 dni otwarcia w&nbsp;roku. Ceny biletów jednodniowych na 2027 rok jeszcze nie są opublikowane, na stronie jest na razie tylko karnet AWESOME.</p>
<h2>Legoland czy LEGO House</h2>
<p>To dwa różne miejsca i&nbsp;łatwo je pomylić już na etapie planowania. LEGO House stoi w&nbsp;centrum Billund, przy Ole Kirks Plads 1, około 1,5&nbsp;km pieszo od bramy Legolandu (niecałe 20 minut).</p>
<p>To cztery strefy zabawy z&nbsp;budowaniem z&nbsp;klocków, sklep, restauracja i&nbsp;w&nbsp;każdej strefie kącik DUPLO dla najmłodszych. Bilety kosztują od 219&nbsp;DKK, online o&nbsp;30&nbsp;DKK taniej. Dzieci od 0 do 2 lat wchodzą za darmo, od 3 lat płacą za bilet dziecięcy, a&nbsp;dziecko poniżej 13 lat musi być pod opieką osoby pełnoletniej. Przeciętna wizyta trwa 3–4 godziny.</p>
<p>Zwykłe godziny LEGO House od października do grudnia 2026: strefy działają od poniedziałku do piątku i&nbsp;w&nbsp;niedzielę 10–16, w&nbsp;sobotę 10–17. W&nbsp;ferie jesienne (12–25 października) i&nbsp;27–30 grudnia otwarte jest dłużej – sprawdź dokładne godziny przed wizytą. Zamknięte są 3–4 listopada, 22 listopada oraz 23–26 grudnia.</p>
<p>Wielopoziomowy parking przy Hovedgaden 24, około 100 metrów od wejścia, kosztuje 20&nbsp;DKK za każdą rozpoczętą godzinę. Przy drugim parkingu, na Granvej 9, strony się nie zgadzają: strona z&nbsp;dojazdem podaje 15&nbsp;DKK za rozpoczętą godzinę, a&nbsp;FAQ tego samego operatora twierdzi, że jest bezpłatny. Zanim tam zaparkujesz, sprawdź tablicę na miejscu.</p>
<figure><img src="https://kastrup.cz/images/clanky/legoland-dania/lego-house-1500.webp" alt="Budynek LEGO House w Billund z dużymi klockami przed wejściem" loading="lazy"><figcaption>LEGO House w&nbsp;Billund, październik 2022. Fot. <a href="https://commons.wikimedia.org/wiki/File:Lego_House_Billund.jpg">MPhernambucq</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>. Pomniejszone i przekonwertowane do formatu WebP.</figcaption></figure>
<h2>Jeden dzień czy dwa</h2>
<p>Przy ponad 45 atrakcjach i&nbsp;Minilandzie jeden dzień wystarcza, żeby zobaczyć najważniejsze rzeczy, ale robi się ciasno, jeśli do tego chcesz jeszcze wejść do LEGO House. Bilet dwudniowy kosztuje online od 149&nbsp;DKK więcej niż jednodniowy, a&nbsp;daje zapas na wypadek deszczu albo kolejek – drugi dzień nie musi wypaść zaraz po pierwszym.</p>
<p>W&nbsp;tygodniu wieczornego otwarcia podczas Halloween (10–17 października) masz więcej czasu, bo park zamyka się dopiero o&nbsp;21.</p>
<figure><img src="https://kastrup.cz/images/clanky/legoland-dania/miniland-port-1500.webp" alt="Port z klocków LEGO w Minilandzie w LEGOLAND Billund" loading="lazy"><figcaption>Port w&nbsp;Minilandzie, latem 2022. Fot. <a href="https://commons.wikimedia.org/wiki/File:Billund_Legoland_12.jpg">Andrzej Otrębski</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>. Pomniejszone i przekonwertowane do formatu WebP.</figcaption></figure>
<h2>Jak dojechać z&nbsp;Polski autem</h2>
<p>Trasa z&nbsp;zachodniej Polski wiedzie przez północne Niemcy do Jutlandii. Ze Szczecina do Legolandu jest około 643&nbsp;km, w&nbsp;czystej jeździe jakieś 6 godzin 40 minut, przez autostrady A11, A20 i&nbsp;dalej A7/E45. Z&nbsp;Poznania to około 820&nbsp;km i&nbsp;około 8 godzin 20 minut, przez A2, obwodnicę Berlina A10, A24, A21 i&nbsp;znów A7/E45. Dla porównania: z&nbsp;Wrocławia około 922&nbsp;km, z&nbsp;Gdańska około 943&nbsp;km, z&nbsp;Warszawy około 1132&nbsp;km. To czasy bez postojów i&nbsp;korków wokół Hamburga, więc dolicz swój zapas.</p>
<p>Do nawigacji wpisz adres Nordmarksvej 9, 7190 Billund. Parking przy samym parku (P1, P2, P3, P5, P6) kosztuje 105&nbsp;DKK za dzień, tablicę rejestracyjną system czyta automatycznie przy wjeździe i&nbsp;wyjeździe.</p>
<p>Most Storebælt Cię nie dotyczy: łączy wyspy Fionię i&nbsp;Zelandię na wschód od Billund, więc jadąc z&nbsp;Niemiec w&nbsp;ogóle na niego nie wjeżdżasz. Dopiero gdy po Legolandzie planujesz jechać dalej do Kopenhagi, przyda się nasz artykuł o&nbsp;<a href="/artykul/mosty-w-danii">mostach w&nbsp;Danii</a> z&nbsp;aktualnym cennikiem.</p>
<p>Prom Świnoujście–Ystad, który wygląda na skrót, dla Billund nie ma sensu. Ystad leży w&nbsp;Szwecji, a&nbsp;stamtąd do Legolandu jest jeszcze około 346&nbsp;km trasą przez most Øresund, Zelandię i&nbsp;Fionię, czyli zapłacisz za prom i&nbsp;oba płatne mosty. Na trasie przez Niemcy mogą być opłaty drogowe, sprawdź je przed wyjazdem.</p>
<p>Jeśli zostawiasz sobie zapas czasu i&nbsp;nie spieszysz się prosto na autostradę, rozważ przystanek w&nbsp;<a href="/artykul/ribe">Ribe</a>, uważanym za najstarsze miasto Danii, leżącym w&nbsp;południowo-zachodniej Jutlandii. Jeśli dopiero układasz trasę i&nbsp;chcesz się zorientować, co jeszcze leży po drodze, przyda się nasz <a href="/co-zobaczyc-w-danii">przewodnik po Danii</a>.</p>
<h2>Jak dojechać z&nbsp;Polski samolotem</h2>
<p>Strona lotniska Billund (BLL) wymienia bezpośrednie loty z&nbsp;Gdańska, Katowic i&nbsp;Warszawy. Z&nbsp;Gdańska lata Wizz Air, do 5 razy w&nbsp;tygodniu, od 119&nbsp;DKK w&nbsp;jedną stronę. Z&nbsp;Katowic również Wizz Air, do 4 razy w&nbsp;tygodniu, od 119&nbsp;DKK. Z&nbsp;Warszawy lata LOT, około 1 godziny 40 minut w&nbsp;powietrzu. Starszy komunikat prasowy lotniska podawał jednak niższą częstotliwość, po 3 loty tygodniowo (poniedziałek, środa, piątek) dla obu tras, więc zanim kupisz bilet, sprawdź aktualny rozkład na dany termin. Z&nbsp;Poznania lotnisko podaje tylko połączenie z&nbsp;przesiadką.</p>
<p>Samo lotnisko leży blisko parku: w&nbsp;linii prostej to około 1,9&nbsp;km, autem około 4,7&nbsp;km. Do LEGO House jest nieco dalej, jego własna strona podaje około 3&nbsp;km. Spod terminalu odjeżdżają autobusy regionalne (m.in. do Vejle, Kolding, Esbjergu i&nbsp;Aarhus) oraz Flixbus do Kopenhagi, a&nbsp;przystanek przy samym Legolandzie park opisuje jako „tuż przed wejściem”.</p>
<figure><img src="https://kastrup.cz/images/clanky/legoland-dania/miniland-lotnisko-1500.webp" alt="Makieta lotniska z klocków LEGO w Minilandzie" loading="lazy"><figcaption>Lotnisko z&nbsp;klocków w&nbsp;Minilandzie, latem 2022. Fot. <a href="https://commons.wikimedia.org/wiki/File:Billund_Legoland_13.jpg">Andrzej Otrębski</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>. Pomniejszone i przekonwertowane do formatu WebP.</figcaption></figure>
<h2>Gdzie spać</h2>
<p>W&nbsp;samym resorcie stoją trzy obiekty. Hotel LEGOLAND (Aastvej 10) ma cztery gwiazdki i&nbsp;pokoje w&nbsp;klimacie LEGO, stoi tuż przy parku. LEGOLAND Castle Hotel (Aastvej 20) wygląda jak zamek, ma 142 baśniowe pokoje i&nbsp;własne wejście prosto do parku. LEGOLAND Holiday Village (Ellehammers Allé 2) to kemping z&nbsp;chatkami w&nbsp;stylu Dzikiego Zachodu i&nbsp;pokojami Pirates' Inn, w&nbsp;odległości spacerowej od parku. Przy hotelach parkują tylko goście z&nbsp;zezwoleniem. Z&nbsp;kartą parkingową albo karnetem EXTREME parkowanie jest bezpłatne. Cen noclegów celowo nie podajemy, zmieniają się razem z&nbsp;terminem i&nbsp;dostępnością.</p>
<p>Jeśli po Legolandzie jedziesz dalej w&nbsp;stronę Kopenhagi, skorzystaj z&nbsp;naszego zestawienia <a href="/noclegi">noclegów</a> i&nbsp;zerknij na przewodniki <a href="/artykul/kopenhaga-z-dziecmi">Kopenhaga z&nbsp;dziećmi</a> oraz <a href="/artykul/tivoli-kopenhaga">Tivoli w&nbsp;Kopenhadze</a>. Nasze zestawienie dotyczy głównie Kopenhagi, więc nocleg przy parku najlepiej szukaj bezpośrednio pod swój termin.</p>
<h2>Jedzenie i&nbsp;zasady w&nbsp;parku</h2>
<p>Własne jedzenie i&nbsp;picie możesz wnieść, park ma nawet wyznaczone miejsca piknikowe. Zakazany jest za to sprzęt do grillowania. Ze zwierząt wejdą tylko psy: na krótkiej smyczy (nie automatycznej) i&nbsp;nigdy bez opieki. Z&nbsp;psem nie wsiądziesz do atrakcji ani nie wejdziesz do środka restauracji, ogródki są w&nbsp;porządku. Psów przewodników te ograniczenia nie dotyczą. Zakazane są też hulajnogi, rowery i&nbsp;wrotki (poza sprzętem dla osób z&nbsp;niepełnosprawnością) oraz drony. Przy głównym wejściu możliwa jest kontrola bagażu, a&nbsp;palenie, także e-papierosów, jest dozwolone tylko w&nbsp;wyznaczonych miejscach.</p>
<h2>Na czym można się przejechać</h2>
<p>Kilka rzeczy, przez które łatwo zepsuć sobie rodzinny wyjazd, jeśli się o&nbsp;nich nie wie z&nbsp;wyprzedzeniem:</p>
<ul><li>Bilet kupiony dopiero na bramie zamiast wcześniej online – do 170&nbsp;DKK więcej na osobę.</li><li>Przyjazd między 2 a&nbsp;27 listopada – park jest wtedy zamknięty.</li><li>Drugi dzień dwudniowego biletu odłożony „na kiedyś” – ważność kończy się po 6 dniach od pierwszej wizyty.</li><li>Plan „zostajemy do samego zamknięcia” – atrakcje przestają działać godzinę wcześniej niż brama.</li><li>Prom Świnoujście–Ystad zamiast trasy przez Niemcy – to nie skrót, od Ystad zostaje jeszcze około 346&nbsp;km i&nbsp;dwa płatne mosty.</li><li>Traktowanie LEGO House jako części Legolandu – to osobny bilet, mimo że dzieli je niecałe półtora kilometra pieszo.</li></ul>
<h2>Często zadawane pytania</h2>
<h3>Ile kosztuje Legoland w&nbsp;Danii?</h3>
<p>Bilet jednodniowy online zaczyna się od 349&nbsp;DKK, na bramie kosztuje 519&nbsp;DKK. Bilet dwudniowy online od 498&nbsp;DKK. Bilet łączony z&nbsp;LEGO House kosztuje online od 649&nbsp;DKK, a&nbsp;według parku osobne bilety kosztują razem 878&nbsp;DKK. Dzieci poniżej 2 lat wchodzą bezpłatnie.</p>
<h3>Kiedy jest otwarty Legoland w&nbsp;2026 roku?</h3>
<p>Do 1 listopada park działa prawie codziennie, zamknięty jest tylko 29–30 września oraz 1, 6–8 i&nbsp;28–29 października. Od 2 do 27 listopada jest całkowicie zamknięty, a&nbsp;od 28 listopada do 31 grudnia działa w&nbsp;wybrane dni, z&nbsp;przerwą 24–26 grudnia. Terminu startu sezonu 2027 park jeszcze nie ogłosił.</p>
<h3>Ile kilometrów jest z&nbsp;Polski do Legolandu?</h3>
<p>Ze Szczecina do Billund jest około 643&nbsp;km, z&nbsp;Poznania około 820&nbsp;km, z&nbsp;Wrocławia około 922&nbsp;km, z&nbsp;Gdańska około 943&nbsp;km, a&nbsp;z&nbsp;Warszawy około 1132&nbsp;km. Trasa prowadzi przez Niemcy, bez promu i&nbsp;bez mostu Storebælt.</p>
<h3>Czy można wnieść własne jedzenie do parku?</h3>
<p>Tak, park pozwala wnosić jedzenie i&nbsp;napoje i&nbsp;ma wyznaczone miejsca piknikowe. Jedyne, czego nie wniesiesz, to sprzęt do grillowania.</p>
<h3>Od ilu lat warto jechać do Legolandu?</h3>
<p>Park sam pisze o&nbsp;dzieciach od 3 do 12 lat jako o&nbsp;głównej grupie, ale dodaje, że jest ciekawym miejscem dla rodzin w&nbsp;każdym wieku. Przy poszczególnych atrakcjach obowiązują osobne limity wzrostu. Znajdziesz je na miejscu i&nbsp;w&nbsp;aplikacji parku.</p>
<p>Źródła: legoland.dk (cennik, kalendarz otwarcia, opis parku), legohouse.com (cennik, godziny, dojazd), bll.dk (połączenia lotnicze), servicecenter.legoland.dk (regulamin, parking), własne obliczenia tras i&nbsp;odległości na podstawie OpenStreetMap i&nbsp;OSRM. Sprawdzone 28 września 2026, przed wyjazdem zajrzyj jeszcze raz do aktualnego cennika i&nbsp;kalendarza.</p>$pl$, $pl$Legoland Dania: ceny i godziny 2026 | Kastrup.pl$pl$, $pl$Legoland Dania: ile kosztuje bilet online i na bramie, kiedy park jest otwarty w 2026 i jak dojechać z Polski autem lub samolotem. Dane z 28 września.$pl$, $pl$legoland dania$pl$, 'cbf723ca-1307-4ffd-8717-5b673c8643cd', '415c2012-9d88-4267-9b21-63b93ab384ad', $pl$https://kastrup.cz/images/clanky/legoland-dania/wejscie-1500.webp$pl$, $pl$https://kastrup.cz/images/clanky/legoland-dania/wejscie-1500.webp$pl$, false)
on conflict (lang, slug) do update set title=excluded.title, perex=excluded.perex, content=excluded.content, meta_title=excluded.meta_title,
  meta_description=excluded.meta_description, focus_keyword=excluded.focus_keyword, image_url=excluded.image_url, og_image=excluded.og_image, updated_at=now()
returning slug, published, length(content) as len, md5(content) as md5;

insert into public.articles (lang, translation_of, slug, title, perex, content, meta_title, meta_description, focus_keyword, category_id, author_id, image_url, og_image, published)
values ('pl', null, $pl$kopenhaga-z-dziecmi$pl$, $pl$Kopenhaga z dziećmi: co robić według wieku i ile to kosztuje$pl$, $pl$Sprawdź, co robić w Kopenhadze z dziećmi w zależności od wieku, gdzie się schować przed deszczem i co jest za darmo. Policzyliśmy też, czy Copenhagen Card w ogóle opłaca się rodzinie, i sprawdziliśmy, jak jeździć komunikacją miejską z dziećmi i wózkiem.$pl$, $pl$<p>Samolot wylądował w&nbsp;Kastrupie, bagaże już krążą na taśmie, a&nbsp;starsze dziecko pyta, czy dziś będzie padać. Sprawdzasz pogodę w&nbsp;telefonie: deszcz do południa. Młodsze dziecko domaga się jedzenia, więc pierwsza rzecz, jaką kupujesz w&nbsp;Danii, to hot dog przy stacji metra na lotnisku. I&nbsp;od razu pierwszy cenowy szok tego wyjazdu.</p>
<p><strong>Ceny sprawdzone 28 września 2026</strong>, w&nbsp;koronach duńskich (DKK, czasem zapisywanych jako kr.), bez przeliczeń na złote.</p>
<p><em>Zdjęcie tytułowe: Den Blå Planet w&nbsp;Kastrup. Zdjęcie archiwalne, 2017. Fot. <a href="https://commons.wikimedia.org/wiki/File:National_Aquarium_Denmark,_Kastrup,_Denmark_(Unsplash).jpg">Sandro Katalina sandrokatalina</a>, <a href="http://creativecommons.org/publicdomain/zero/1.0/deed.en">CC0</a>. Pomniejszone i przekonwertowane do formatu WebP.</em></p>
<h2>Co robić z&nbsp;dziećmi w&nbsp;zależności od wieku</h2>
<h3>Niemowlęta i&nbsp;maluchy (0–3 lata)</h3>
<p>Z&nbsp;najmłodszym dzieckiem szukasz przede wszystkim miejsca, gdzie maluch może się swobodnie ruszać, a&nbsp;Ty nie musisz go pilnować co chwilę.</p>
<ul><li><strong>Den Blå Planet</strong>, duńskie akwarium narodowe, stoi ok. 600 metrów (ok. 10 minut pieszo) od stacji metra Kastrup – dobry pierwszy albo ostatni przystanek w&nbsp;podróży. Budynek ma windy i&nbsp;platformy (nie wszędzie jest to jednak w&nbsp;pełni bezbarierowe) oraz bezpłatne wózki inwalidzkie do wypożyczenia po wcześniejszej rezerwacji, najpóźniej dzień przed wizytą. Dotykowy basen z&nbsp;płaszczkami i&nbsp;rozgwiazdami lubią też najmłodsi. Bilet dla dorosłego kosztuje 249&nbsp;DKK (online 219&nbsp;DKK), bilet dziecięcy (3–11 lat) 131&nbsp;DKK (online 116&nbsp;DKK), a&nbsp;dzieci do 2 lat wchodzą za darmo. W&nbsp;weekendy i&nbsp;w&nbsp;szczycie sezonu ceny są nieco wyższe (259 i&nbsp;136&nbsp;DKK, online 229 i&nbsp;123&nbsp;DKK). Więcej o&nbsp;samym Kastrupie i&nbsp;pobliskiej plaży piszemy w&nbsp;<a href="/artykul/kastrup">osobnym artykule</a>.</li><li><strong>Experimentarium</strong> w&nbsp;Hellerup ma osobną strefę zabaw Miniverset, pomyślaną dla dzieci od 1 do 5 lat. Bilety online: 230&nbsp;DKK od 12 lat, 143&nbsp;DKK dla dzieci 2–11 lat, młodsze wchodzą za darmo; ceny zależą od dnia.</li><li><strong>Islands Brygge Havnebad</strong> latem – płytki basenik dla najmłodszych (Småbørnsbassin, 18×6&nbsp;m, głębokość 10–70&nbsp;cm), wstęp wolny; ratownik dyżuruje tylko od 1 czerwca do 31 sierpnia, 10–18. Jakość wody sprawdzisz na kk.dk; jeśli stojąc po kolana nie widzisz stóp, lepiej nie wchodzić.</li></ul>
<h3>Przedszkolaki (4–7 lat)</h3>
<p>W&nbsp;tym wieku dzieci chcą wszystko robić same, więc sprawdzają się miejsca, gdzie można się wybiegać i&nbsp;coś zbudować.</p>
<figure><img src="https://kastrup.cz/images/clanky/kopenhaga-z-dziecmi/rundetaarn-rampa-1500.webp" alt="Spiralna rampa wewnątrz wieży Rundetaarn w Kopenhadze" loading="lazy"><figcaption>Rampa w&nbsp;Rundetaarn. Zdjęcie archiwalne, 2011. Fot. <a href="https://commons.wikimedia.org/wiki/File:002_Copenhagen_landmark_-_The_Round_Tower_(Rundetaarn)_spiral_ramp.jpg">Marek Ślusarczyk (Tupungato) Photo portfolio</a>, <a href="https://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>. Pomniejszone i przekonwertowane do formatu WebP.</figcaption></figure>
<ul><li><strong>Rundetaarn</strong> – dzieci poniżej 18 lat wchodzą za darmo (dorosły płaci 60&nbsp;DKK, bilet tylko na miejscu), a&nbsp;na szczyt nie prowadzą schody, tylko spiralna rampa (7,3 obrotu, 281 metrów, nachylenie 10%), po której da się iść albo biec. Dzieci do 11 lat muszą iść z&nbsp;dorosłym. Ostatni odcinek na platformę to wąskie, kręte schody.</li><li><strong>Tårnlegepladsen</strong> w&nbsp;Fælledparku – plac zabaw z&nbsp;miniaturami kopenhaskich wież (m.in. wieży Vor Frelsers Kirke, ratusza i&nbsp;Rundetaarn) połączonych kładkami i&nbsp;zjeżdżalniami. W&nbsp;dni powszednie dyżurują tu pedagodzy, a&nbsp;toaleta i&nbsp;przewijak są dostępne także poza tymi godzinami.</li><li><strong>Experimentarium</strong>, strefa Legedalen (3–6 lat).</li><li><strong>LEGO Store</strong> przy Vimmelskaftet 37 na Strøget – ściana Pick &amp; Build i&nbsp;stanowisko do budowania własnej minifigurki, otwarte pon.–sob. 10–18, w&nbsp;niedziele 11–17.</li></ul>
<h3>Starsze dzieci (8–12 lat)</h3>
<figure><img src="https://kastrup.cz/images/clanky/kopenhaga-z-dziecmi/zoo-wieza-wielblad-1500.webp" alt="Wielbłąd na wybiegu i wieża widokowa w zoo w Kopenhadze" loading="lazy"><figcaption>Zoo w&nbsp;Kopenhadze z&nbsp;wieżą widokową. Zdjęcie archiwalne, 2012. Fot. <a href="https://commons.wikimedia.org/wiki/File:Copenhagen_Zoo_Tower_and_camel.jpg">Guillaume Baviere from Helsingborg, Sweden</a>, <a href="https://creativecommons.org/licenses/by/2.0">CC BY 2.0</a>. Pomniejszone i przekonwertowane do formatu WebP.</figcaption></figure>
<ul><li><strong>Zoo København</strong> (Roskildevej 32, Frederiksberg) – bilet dla dorosłego 260&nbsp;DKK, dziecięcy (3–14 lat) 160&nbsp;DKK, ważny rok od zakupu; ceny zmieniają się w&nbsp;zależności od sezonu. Wejście na Zootårnet, wieżę widokową w&nbsp;zoo, kosztuje dodatkowo 25&nbsp;DKK. W&nbsp;październiku zoo jest otwarte codziennie 9–17, od listopada do lutego krócej, 10–16.</li><li><strong>Nationalmuseet i&nbsp;Børnenes Museum</strong> – dzieci poniżej 18 lat wchodzą za darmo, dorosły płaci 150&nbsp;DKK (online 135&nbsp;DKK). W&nbsp;dziecięcej części czeka wikińska łódź Fafner ze strojami do przebierania, pakistański bazar i&nbsp;średniowieczny zamek. Børnenes Museum zamyka się o&nbsp;16.30, pół godziny wcześniej niż reszta muzeum. Muzeum jest zamknięte 24, 25 i&nbsp;31 grudnia.</li><li><strong>Rejs po kanałach</strong> – Netto-Bådene z&nbsp;Nyhavn (dorosły 80&nbsp;DKK, dziecko 3–14 lat 40&nbsp;DKK, bez rezerwacji) albo Stromma (z&nbsp;Nyhavn od 169&nbsp;DKK za dorosłego, dzieci 6–15 lat płacą połowę, młodsze płyną za darmo).</li></ul>
<h2>Kiedy pada deszcz</h2>
<p>W&nbsp;Kopenhadze jest parę miejsc, w&nbsp;których przesiedzisz kilka godzin bez patrzenia na niebo.</p>
<figure><img src="https://kastrup.cz/images/clanky/kopenhaga-z-dziecmi/experimentarium-1500.webp" alt="Budynek centrum nauki Experimentarium w Hellerup" loading="lazy"><figcaption>Experimentarium w&nbsp;Hellerup. Zdjęcie archiwalne. Fot. <a href="https://commons.wikimedia.org/wiki/File:20171005_Experimentarium_Hellerup_0062_(37729624156).jpg">Johan Wessman / News Oresund</a>, <a href="https://creativecommons.org/licenses/by/2.0">CC BY 2.0</a>. Pomniejszone i przekonwertowane do formatu WebP.</figcaption></figure>
<p><strong>Den Blå Planet</strong> i&nbsp;<strong>Experimentarium</strong> (otwarte codziennie 9.30–17 przez cały rok, 24 i&nbsp;31 grudnia tylko do 14) to najpewniejsze opcje. <strong>Nationalmuseet z&nbsp;Børnenes Museum</strong> też się sprawdzi, ale od listopada do marca jest zamknięte w&nbsp;poniedziałki. LEGO Store starczy na jakieś pół godziny, ale jako przerwa w&nbsp;środku spaceru się sprawdza.</p>
<h2>Co jest za darmo</h2>
<figure><img src="https://kastrup.cz/images/clanky/kopenhaga-z-dziecmi/islands-brygge-kapielisko-1500.webp" alt="Kąpielisko portowe Islands Brygge latem pełne ludzi" loading="lazy"><figcaption>Islands Brygge Havnebad, lipiec 2026. Fot. <a href="https://commons.wikimedia.org/wiki/File:Islands_Brygge_Havnebad_K%C3%B8benhavn.jpeg">kallerna</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>. Pomniejszone i przekonwertowane do formatu WebP.</figcaption></figure>
<p>Kilka rzeczy w&nbsp;Kopenhadze naprawdę nic nie kosztuje: wejście na <strong>Rundetaarn</strong> dla dzieci poniżej 18 lat, wstęp do <strong>Nationalmuseet i&nbsp;Børnenes Museum</strong> dla osób poniżej 18 lat (dorosły płaci 150&nbsp;DKK), publiczny plac zabaw <strong>Tårnlegepladsen</strong> w&nbsp;Fælledparku, bez biletów i&nbsp;bramek, oraz kąpielisko <strong>Islands Brygge Havnebad</strong>, otwarte codziennie 6–22 przez cały rok.</p>
<h2>Czy opłaca się Copenhagen Card dla rodziny</h2>
<p>Copenhagen Card kupisz w&nbsp;wariancie Discover (z&nbsp;komunikacją miejską w&nbsp;całym regionie, także z&nbsp;lotniska) albo Hop (bez komunikacji miejskiej, ale z&nbsp;autobusami hop-on hop-off). Ceny Discover na 24 godziny: dorosły (od 16 lat) 589&nbsp;DKK, junior (12–15 lat) 399&nbsp;DKK, dziecko (3–11 lat, „Kids”) 100&nbsp;DKK; najwyżej dwie karty Kids na jedną kartę dorosłego, kupione w&nbsp;tym samym zamówieniu, inaczej ich nie dokupisz. Na pytanie, czy dzieci dostają kartę gratis, operator odpowiada w&nbsp;FAQ krótko: nie. Dzieci do 2 lat w&nbsp;ogóle jej nie potrzebują.</p>
<figure><img src="https://kastrup.cz/images/clanky/kopenhaga-z-dziecmi/nationalmuseet-1500.webp" alt="Gmach Nationalmuseet nad kanałem w centrum Kopenhagi" loading="lazy"><figcaption>Nationalmuseet. Zdjęcie archiwalne, 2018. Fot. <a href="https://commons.wikimedia.org/wiki/File:Nationalmuseet_20180721.jpg">Suicasmo</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>. Pomniejszone i przekonwertowane do formatu WebP.</figcaption></figure>
<p>Ważne zastrzeżenie: <strong>Rundetaarn nie jest objęty Copenhagen Card</strong>. Od 1 kwietnia 2024 wieża wypadła z&nbsp;listy atrakcji karty – mówi o&nbsp;tym wprost strona wieży. Jeśli w&nbsp;planie masz właśnie Rundetaarn, dolicz do niego osobny bilet, karta go nie pokryje.</p>
<p>Policzmy to na przykładzie dwóch atrakcji, które karta rzeczywiście obejmuje: rodzina 2+2, dzieci w&nbsp;wieku 5 i&nbsp;9 lat, jeden dzień w&nbsp;mieście z&nbsp;Zoo i&nbsp;Experimentarium. Bilety osobno: do zoo (2 × 260 + 2 × 160 = 840&nbsp;DKK) i&nbsp;do Experimentarium (online 2 × 230 + 2 × 143 = 746&nbsp;DKK, cena zależy od dnia) dają razem 1586&nbsp;DKK. Copenhagen Card Discover na 24 godziny dla tej samej rodziny (2 × 589 + 2 × 100) kosztuje 1378&nbsp;DKK, czyli o&nbsp;208&nbsp;DKK mniej, jeszcze bez liczenia przejazdów.</p>
<p>Do transportu dwoje dzieci poniżej 12 lat jedzie z&nbsp;dorosłym za darmo na dowolny bilet, nie tylko na City Pass, więc doliczasz jedynie bilety dla dorosłych. Trzy przejazdy w&nbsp;dwóch strefach (2 × 24&nbsp;DKK za każdy) to kolejne 144&nbsp;DKK, razem 1730&nbsp;DKK bez karty. Wtedy Copenhagen Card z&nbsp;komunikacją miejską w&nbsp;cenie (1378&nbsp;DKK) wychodzi taniej o&nbsp;352&nbsp;DKK. Oficjalna strona zastrzega, że ceny mogą się zmienić bez zapowiedzi, więc przelicz to jeszcze raz tuż przed wyjazdem.</p>
<h2>Komunikacja miejska z&nbsp;dziećmi i&nbsp;wózkiem</h2>
<p>Dzieci do 15 lat płacą za bilet jednorazowy połowę ceny dorosłego, ale dwoje dzieci poniżej 12 lat jedzie z&nbsp;dorosłym za darmo na dowolny bilet, nie tylko na City Pass – to ogólna zasada DOT, nie przywilej samego City Passu. Bilet na dwie strefy kosztuje 24&nbsp;DKK, na trzy strefy (czyli na przykład z&nbsp;lotniska do centrum) 30&nbsp;DKK i&nbsp;jest ważny półtorej godziny; metro M2 z&nbsp;lotniska do centrum jedzie 14 minut. City Pass ma sens raczej wtedy, gdy jeździcie dużo tego samego dnia i&nbsp;nie chcecie za każdym razem kupować pojedynczych biletów; dzieci 12–15 lat płacą na niego połowę ceny. Szczegóły dojazdu, cen i&nbsp;nocnych kursów opisaliśmy w&nbsp;<a href="/artykul/lotnisko-kopenhaga-dojazd-do-centrum">przewodniku po lotnisku Kastrup</a>.</p>
<p>Windy podaje strona przewoźnika m.dk przy wszystkich 44 stacjach metra, od jednej (Kastrup) po sześć (Kongens Nytorv) – z&nbsp;wózkiem wejdziesz więc bez większego problemu. Na łódź Stromma wózka nie wniesiesz – przewoźnik wprost pisze, że to niemożliwe. Wózek możesz zostawić na nabrzeżu na własne ryzyko, przewoźnik radzi przypiąć go własnym zapięciem. Na łodziach nie ma też toalety.</p>
<h2>Co jest sezonowe i&nbsp;co zimą zamknięte</h2>
<p>Łodzie Netto-Bådene pływają cały rok (od października do marca kryte i&nbsp;ogrzewane), ale przy zamarzniętym porcie nie kursują wcale – w&nbsp;2026 roku wznowiły kursy dopiero 5 marca, gdy port rozmarzł. Według strony wieży obserwatorium na szczycie Rundetaarn jest w&nbsp;2026 roku zamknięte z&nbsp;powodu renowacji, choć w&nbsp;sklepie z&nbsp;biletami wciąż widnieją terminy wieczornych obserwacji. Jeśli na nie liczysz, zapytaj w&nbsp;kasie.</p>
<h2>Czego lepiej unikać</h2>
<ul><li>Kupowania Copenhagen Card tylko dla dorosłych w&nbsp;przekonaniu, że dzieci wejdą z&nbsp;wami za darmo – dziecko 3–11 lat potrzebuje karty Kids, którą trzeba dokupić w&nbsp;tym samym zamówieniu co kartę dorosłego (100&nbsp;DKK za 24 godziny).</li><li>Liczenia na to, że Copenhagen Card pokryje Rundetaarn – od 2024 roku wieża wypadła z&nbsp;listy atrakcji karty, bilet trzeba dokupić osobno.</li><li>Przyjazdu do Nationalmuseet w&nbsp;poniedziałek między listopadem a&nbsp;marcem – wtedy muzeum jest zamknięte, poza jednym tygodniem w&nbsp;lutym i&nbsp;Wielkanocą.</li><li>Liczenia na rejs Netto-Bådene w&nbsp;mroźny dzień – przy zamarzniętym porcie łodzie nie wypływają.</li><li>Planu wizyty w&nbsp;Tivoli na przełomie września i&nbsp;października albo na początku listopada – akurat wtedy ogrody stoją zamknięte między sezonami.</li></ul>
<h2>Tivoli i&nbsp;Legoland, jeśli zostanie Ci czas</h2>
<p>Jeśli w&nbsp;planie masz też Ogrody Tivoli, sprawdź najpierw kalendarz sezonów i&nbsp;limity wzrostu na atrakcjach w&nbsp;naszym <a href="/artykul/tivoli-kopenhaga">przewodniku po Tivoli</a>. Między sezonami park stoi zamknięty: do 1 października i&nbsp;od 2 do 12 listopada 2026. Legoland w&nbsp;Billund leży w&nbsp;środku Jutlandii, po drugiej stronie kraju niż Kopenhaga, więc to raczej osobny wyjazd niż dodatek do jednego dnia w&nbsp;mieście; ceny biletów i&nbsp;kalendarz otwarcia opisaliśmy w&nbsp;<a href="/artykul/legoland-dania">przewodniku po Legolandzie</a>.</p>
<figure><img src="https://kastrup.cz/images/clanky/kopenhaga-z-dziecmi/rejs-kanalami-1500.webp" alt="Łódź wycieczkowa płynąca kanałem w Kopenhadze" loading="lazy"><figcaption>Łódź z&nbsp;rejsami po kanałach. Zdjęcie archiwalne, 2015. Fot. <a href="https://commons.wikimedia.org/wiki/File:Canal_Tours_in_Nyhavn_01.JPG">Leif Jørgensen</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>. Pomniejszone i przekonwertowane do formatu WebP.</figcaption></figure>
<p>Jeśli dopiero układasz resztę trasy, zerknij też do naszego <a href="/kopenhaga">przewodnika po Kopenhadze</a> i&nbsp;<a href="/noclegi">zestawienia noclegów</a> blisko centrum.</p>
<h2>Najczęściej zadawane pytania</h2>
<p><strong>Czy Copenhagen Card opłaca się rodzinie z&nbsp;dziećmi?</strong> Częściej, niż mogłoby się wydawać, ale nie zawsze. W&nbsp;naszym przykładzie (rodzina 2+2, bilety do zoo i&nbsp;Experimentarium plus kilka przejazdów komunikacją miejską) osobne bilety kosztują 1730&nbsp;DKK, karta 1378&nbsp;DKK – oszczędzasz 352&nbsp;DKK. Uważaj tylko na Rundetaarn: karta go nie obejmuje, tam dopłacisz osobno. Policz to dla swojego planu.</p>
<p><strong>Co robić z&nbsp;dziećmi w&nbsp;Kopenhadze, gdy pada deszcz?</strong> Den Blå Planet, Experimentarium i&nbsp;Nationalmuseet z&nbsp;Børnenes Museum mają dachy nad głową na kilka godzin. Experimentarium jest otwarte codziennie przez cały rok, a&nbsp;Nationalmuseet od listopada do marca bywa zamknięte w&nbsp;poniedziałki.</p>
<p><strong>Czy dzieci jeżdżą kopenhaską komunikacją za darmo?</strong> Częściowo. Na bilet jednorazowy dwoje dzieci poniżej 12 lat jedzie z&nbsp;dorosłym za darmo – to ogólna zasada, nie tylko City Passu. Starsze i&nbsp;kolejne dzieci płacą połowę ceny dorosłego.</p>
<p><strong>Czy z&nbsp;wózkiem wejdę na wieżę Rundetaarn?</strong> Częściowo. Rampą da się wjechać, ale to 281 metrów pod górę ze spadkiem 10%, a&nbsp;na sam taras widokowy prowadzą już tylko wąskie schody. Oficjalna strona wieży pisze, że miejsce nie nadaje się dobrze dla wózków.</p>
<p><strong>Co w&nbsp;Kopenhadze jest dla dzieci za darmo?</strong> Wieża Rundetaarn dla dzieci poniżej 18 lat, wstęp do Nationalmuseet i&nbsp;Børnenes Museum dla osób poniżej 18 lat (dorosły płaci 150&nbsp;DKK), plac zabaw Tårnlegepladsen w&nbsp;Fælledparku i&nbsp;kąpielisko Islands Brygge Havnebad, otwarte cały rok.</p>
<p><strong>Źródła:</strong> zoo.dk i&nbsp;shop.zoo.dk (Zoo København), experimentarium.dk (Experimentarium), nationalmuseet.dk (Nationalmuseet, Børnenes Museum), rundetaarn.dk (Rundetaarn), lego.com (LEGO Store), legeplads.kk.dk (Tårnlegepladsen), copenhagencard.com (Copenhagen Card), havnerundfart.dk i&nbsp;stromma.com (rejsy po kanałach), svoemkbh.kk.dk (Islands Brygge Havnebad), m.dk i&nbsp;dinoffentligetransport.dk (komunikacja miejska, windy w&nbsp;metrze, dzieci w&nbsp;komunikacji), tivoli.dk i&nbsp;shop.tivoli.dk (Ogrody Tivoli). Ceny i&nbsp;godziny sprawdzone 28 września 2026.</p>$pl$, $pl$Kopenhaga z dziećmi: atrakcje i ceny 2026 | Kastrup.pl$pl$, $pl$Kopenhaga z dziećmi: atrakcje według wieku, co robić w deszczu, co jest za darmo i czy opłaca się Copenhagen Card. Ceny sprawdzone 28 września 2026.$pl$, $pl$kopenhaga z dziećmi$pl$, 'cbf723ca-1307-4ffd-8717-5b673c8643cd', '415c2012-9d88-4267-9b21-63b93ab384ad', $pl$https://kastrup.cz/images/clanky/kopenhaga-z-dziecmi/den-bla-planet-1500.webp$pl$, $pl$https://kastrup.cz/images/clanky/kopenhaga-z-dziecmi/den-bla-planet-1500.webp$pl$, false)
on conflict (lang, slug) do update set title=excluded.title, perex=excluded.perex, content=excluded.content, meta_title=excluded.meta_title,
  meta_description=excluded.meta_description, focus_keyword=excluded.focus_keyword, image_url=excluded.image_url, og_image=excluded.og_image, updated_at=now()
returning slug, published, length(content) as len, md5(content) as md5;
