insert into public.articles (lang, slug, title, perex, content, meta_title, meta_description, focus_keyword, category_id, author_id, image_url, published)
values ('pl', $k$copenhagen-card$k$, $k$Copenhagen Card 2026: czy się opłaca? Ceny i wyliczenia dla trzech planów$k$, $k$Copenhagen Card na 24 godziny kosztuje dorosłego 589 DKK i nie każdemu się zwraca. Policzyliśmy trzy plany: jeden dzień dla dorosłego, dwa dni z wypadem do Kronborga i Frederiksborga oraz trzy dni dla rodziny 2+2.$k$, $k$<p>Karta czeka w&nbsp;koszyku: 589&nbsp;DKK za dobę. W&nbsp;drugiej zakładce cennik Rosenborga, w&nbsp;trzeciej Tivoli, a&nbsp;w&nbsp;głowie rachunek, który nie chce się domknąć. Odpowiedź w&nbsp;skrócie: przy trzech płatnych wejściach w&nbsp;ciągu doby wychodzisz mniej więcej na zero, a&nbsp;wyraźnie na plus dopiero od czterech. Najlepiej wychodzi doba z&nbsp;Tivoli lub Zoo i&nbsp;dwa dni z&nbsp;wypadem do Kronborga i&nbsp;Frederiksborga. Przy spokojnych dniach w&nbsp;muzeach, zwłaszcza z&nbsp;dziećmi, karta zwykle się nie zwraca, bo w&nbsp;wielu kopenhaskich muzeach osoby poniżej 18 lat wchodzą za darmo.</p>
<p><strong>Ceny sprawdzone 7 października 2026.</strong> Wszystkie kwoty podajemy w&nbsp;koronach duńskich (DKK), bez przeliczania na złote, bo kurs złotego się waha, a&nbsp;operator karty może zmienić cennik bez uprzedzenia.</p>
<h2>Ile kosztuje Copenhagen Card w&nbsp;2026?</h2>
<p>Copenhagen Card Discover dla dorosłego (od 16 lat) kosztuje 589&nbsp;DKK na 24 godziny, 859&nbsp;DKK na 48 i&nbsp;1039&nbsp;DKK na 72 godziny. Dzieci 3–11 lat potrzebują karty Kids (100&nbsp;DKK na 24 godziny), młodzież 12–15 lat karty Junior (399&nbsp;DKK na 24 godziny). Ceny pochodzą z&nbsp;<a href="https://copenhagencard.com/view/prices">oficjalnego cennika karty</a>.</p>
<table><thead><tr><th>Karta (ceny w&nbsp;DKK)</th><th>24&nbsp;h</th><th>48&nbsp;h</th><th>72&nbsp;h</th><th>96&nbsp;h</th><th>120&nbsp;h</th></tr></thead><tbody><tr><td>Discover, dorosły (od 16 lat)</td><td>589</td><td>859</td><td>1039</td><td>1219</td><td>1419</td></tr><tr><td>Discover Junior (12–15 lat)</td><td>399</td><td>509</td><td>589</td><td>699</td><td>789</td></tr><tr><td>Discover Kids (3–11 lat)</td><td>100</td><td>140</td><td>180</td><td>220</td><td>260</td></tr><tr><td>Hop, dorosły</td><td>600</td><td>875</td><td>1050</td><td>brak</td><td>brak</td></tr><tr><td>Hop Junior</td><td>410</td><td>525</td><td>600</td><td>brak</td><td>brak</td></tr><tr><td>Hop Kids</td><td>100</td><td>140</td><td>180</td><td>brak</td><td>brak</td></tr></tbody></table>
<p>Dwie rzeczy łatwo tu pomylić. Ceny 600, 875 i&nbsp;1050&nbsp;DKK to nie Discover, tylko Hop. I&nbsp;dzieci nie dostają karty za darmo: na pytanie, czy dzieci można zabrać za darmo, FAQ operatora odpowiada krótkim „No”. Na dziecko 3–11 lat kupujesz kartę Kids, najwyżej dwie na jedną kartę dorosłego i&nbsp;w&nbsp;tym samym zamówieniu. Na kolejne dzieci i&nbsp;na młodzież 12–15 lat potrzebna jest karta Junior, a&nbsp;dzieci poniżej 3 lat karty nie potrzebują.</p>
<p><em>Zdjęcie tytułowe: Rosenborg jesienią (zdjęcie z&nbsp;listopada 2025). Fot. <a href="https://commons.wikimedia.org/wiki/File:Rosenborg_Castle_Copenhagen_4.jpg">kallerna</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>. Pomniejszone i przekonwertowane do formatu WebP.</em></p>
<h2>Discover czy Hop: czym się różnią?</h2>
<p>Discover to wariant „wszystko w&nbsp;cenie”: ponad 80 atrakcji i&nbsp;komunikacja miejska w&nbsp;całym regionie stołecznym, także z&nbsp;lotniska. Hop ma ponad 40 atrakcji w&nbsp;centrum i&nbsp;autobusy hop-on hop-off firmy Stromma, ale bez komunikacji miejskiej. Hop jest przy tym droższy o&nbsp;11–16&nbsp;DKK, zależnie od czasu ważności karty.</p>
<p>To nie błąd w&nbsp;tabeli. Hop daje mniej: nie obejmuje dojazdu z&nbsp;lotniska ani komunikacji miejskiej, a&nbsp;wśród atrakcji brakuje w&nbsp;nim Kronborga, Frederiksborga, Louisiany i&nbsp;Experimentarium. Kupisz go też tylko na 24, 48 i&nbsp;72 godziny. Jeśli nie chodzi Ci akurat o&nbsp;autobusy hop-on hop-off, Discover wychodzi taniej i&nbsp;obejmuje więcej.</p>
<h2>Co obejmuje Copenhagen Card, a&nbsp;czego nie?</h2>
<p>Lista na <a href="https://copenhagencard.com/attractions">stronie atrakcji</a> ma w&nbsp;październiku 2026 87 pozycji w&nbsp;Discover i&nbsp;47 w&nbsp;Hop, przy czym same autobusy hop-on hop-off też są tam osobną pozycją. W&nbsp;obu wariantach są m.in. Rosenborg, Nationalmuseet, Ny Carlsberg Glyptotek, Thorvaldsens Museum, SMK, Designmuseum Danmark, Zoo København, Planetarium, Christiansborg, Home of Carlsberg, wieża Vor Frelsers Kirke i&nbsp;wstęp do Tivoli. Tylko w&nbsp;Discover: Kronborg, Frederiksborg, Experimentarium, Louisiana oraz Vikingeskibsmuseet z&nbsp;katedrą w&nbsp;Roskilde. Z&nbsp;rejsów karta obejmuje Canal Tours Stromma (wyłącznie trasa Classic z&nbsp;Ved Stranden 26, inne odjazdy z&nbsp;dopłatą), a&nbsp;tylko Discover także GoBoat (Islands Brygge 10, 60 minut) i&nbsp;Baadfarten (tylko od maja do września).</p>
<figure><img src="https://kastrup.cz/images/clanky/copenhagen-card/glyptoteka-ogrod-zimowy-1500.webp" alt="Ogród zimowy z palmami w Ny Carlsberg Glyptotek w Kopenhadze" loading="lazy"><figcaption>Ogród zimowy w&nbsp;Ny Carlsberg Glyptotek. Zdjęcie archiwalne, 2012. Fot. <a href="https://commons.wikimedia.org/wiki/File:Winter_garden_-_Ny_Carlsberg_Glyptotek_-_Copenhagen_-_DSC09235.JPG">Daderot</a>, <a href="http://creativecommons.org/publicdomain/zero/1.0/deed.en">CC0</a>. Pomniejszone i przekonwertowane do formatu WebP.</figcaption></figure>
<p>Czego w&nbsp;karcie nie ma, a&nbsp;co łatwo wrzucić do planu z&nbsp;przyzwyczajenia albo z&nbsp;cudzego bloga:</p>
<ul><li>Den Blå Planet. Akwarium nie ma na liście, choć niektóre poradniki wciąż zachwalają je jako „hit karty”. Jest za to małe Øresundsakvariet w&nbsp;Helsingør, tylko w&nbsp;Discover. Rodzina 2+2 z&nbsp;dziećmi 3–11 lat zapłaci w&nbsp;Den Blå Planet na miejscu 760&nbsp;DKK, online 670&nbsp;DKK (dzień powszedni poza sezonem, <a href="https://denblaaplanet.dk/en/visit-us/prices-and-opening-hours/">cennik akwarium</a>). Więcej o&nbsp;akwarium i&nbsp;okolicy w&nbsp;tekście <a href="/artykul/kastrup">o&nbsp;Kastrup</a>.</li><li>Rundetårn: 60&nbsp;DKK, dzieci poniżej 18 lat za darmo. W&nbsp;karcie nie ma go od 1 kwietnia 2024.</li><li>Netto-Bådene, tańszy rejs po kanałach (dorosły 80&nbsp;DKK, dziecko 3–14 lat 40&nbsp;DKK).</li><li>Przejażdżki w&nbsp;Tivoli. Karta otwiera bramę, ale za karuzele płacisz osobno: z&nbsp;kartą dostajesz tylko zniżkę na Ride Pass, której wysokość operator pokazuje dopiero po zalogowaniu (sam Ride Pass na Halloween kosztuje 269–289&nbsp;DKK). Więcej o&nbsp;parku w&nbsp;<a href="/artykul/tivoli-kopenhaga">przewodniku po Tivoli</a>.</li><li>Malmö, bo leży poza regionem stołecznym.</li></ul>
<p>Komunikacja w&nbsp;Discover obejmuje metro, autobusy, kolejkę podmiejską S-tog, pociągi regionalne i&nbsp;lokalne (w&nbsp;tym do Roskilde, Hillerød i&nbsp;Helsingør) oraz autobusy wodne (Havnebussen). Dojazd z&nbsp;lotniska też jest w&nbsp;cenie, a&nbsp;jak wygląda ta trasa w&nbsp;praktyce, opisujemy w&nbsp;tekście o&nbsp;<a href="/artykul/lotnisko-kopenhaga-dojazd-do-centrum">dojeździe z&nbsp;lotniska do centrum</a>. Jedna pułapka: karta musi obowiązywać przez całą jazdę, a&nbsp;jeśli skończy się w&nbsp;połowie trasy, to Twój problem, nie kontrolera.</p>
<h2>Czy Copenhagen Card się opłaca? Trzy wyliczenia</h2>
<p>Rachunek zależy od tego, ile płatnych wejść zmieścisz w&nbsp;czasie ważności karty. Trzy wejścia to punkt zwrotny: wynik waha się od 40&nbsp;DKK na minusie (Rosenborg, Nationalmuseet i&nbsp;rejs) do 71&nbsp;DKK na plusie, gdy zamiast rejsu wejdzie Zoo za 260&nbsp;DKK (Rosenborg, Nationalmuseet, Zoo i&nbsp;City Pass Small to 660&nbsp;DKK). Od czterech wejść zysk robi się wyraźny: Rosenborg, Nationalmuseet, Glyptotek i&nbsp;rejs razem z&nbsp;City Passem Small dają 699&nbsp;DKK, czyli 110&nbsp;DKK oszczędności, a&nbsp;po wymianie Glyptoteki na Tivoli, jak w&nbsp;planie 1, już 160&nbsp;DKK. Przy dwóch dniach z&nbsp;Kronborgiem i&nbsp;Frederiksborgiem oszczędzasz 385&nbsp;DKK. U&nbsp;rodziny 2+2 wszystko zależy od tego, czy w&nbsp;planie są Zoo i&nbsp;Tivoli.</p>
<p>Jak liczyliśmy: ceny biletów w&nbsp;kasie, w&nbsp;nawiasie ceny online lub early bird. Tivoli: 200&nbsp;DKK w&nbsp;zwykły dzień powszedni, 220&nbsp;DKK w&nbsp;weekend i&nbsp;w&nbsp;duńskie ferie jesienne 12–16 października; w&nbsp;sezonie świątecznym od 13 listopada 210 i&nbsp;230&nbsp;DKK (230&nbsp;DKK także 14–23 i&nbsp;25–27 grudnia). Komunikację „bez karty” liczymy jako City Pass DOT, a&nbsp;rejs jako Classic Canal Tour Stromma z&nbsp;Nyhavnu. Bez karty nie musisz płynąć z&nbsp;Ved Stranden: ten sam rejs z&nbsp;Nyhavnu kosztuje od 149&nbsp;DKK, a&nbsp;z&nbsp;kartą płyniesz z&nbsp;Ved Stranden. Wszystkie sumy policzyliśmy sami, to nie dane operatora karty.</p>
<h3>Plan 1: jeden dzień w&nbsp;centrum, dorosły (Discover 24&nbsp;h: 589&nbsp;DKK)</h3>
<table><thead><tr><th>Pozycja</th><th>Cena w&nbsp;kasie, DKK (online)</th></tr></thead><tbody><tr><td>Rosenborg</td><td>150 (140)</td></tr><tr><td>Nationalmuseet</td><td>150 (135)</td></tr><tr><td>Rejs Stromma Classic Canal Tour</td><td>149 (135 early bird)</td></tr><tr><td>Tivoli, wstęp w&nbsp;dzień powszedni</td><td>200</td></tr><tr><td>City Pass Small 24&nbsp;h (z&nbsp;lotniskiem)</td><td>100</td></tr><tr><td>Razem bez karty</td><td>749 (710)</td></tr><tr><td>Oszczędność z&nbsp;kartą</td><td>160 (121)</td></tr></tbody></table>
<p>Zdejmij z&nbsp;tego dnia Tivoli, a&nbsp;zostaje 549&nbsp;DKK, czyli karta jest o&nbsp;40&nbsp;DKK droższa od osobnych biletów, a&nbsp;z&nbsp;cenami online (510&nbsp;DKK) o&nbsp;79&nbsp;DKK. Zostaw Tivoli, ale zdejmij rejs: wychodzi 600&nbsp;DKK i&nbsp;11&nbsp;DKK zysku, a&nbsp;z&nbsp;cenami online (575&nbsp;DKK) karta jest o&nbsp;14&nbsp;DKK droższa. Cały rachunek trzyma się więc na czterech punktach, a&nbsp;najmniej pewnym z&nbsp;nich jest Tivoli, które od 2 do 12 listopada 2026 jest zamknięte.</p>
<p>Rejs Classic Canal Tour pływa cały rok. Od października do stycznia pierwszy rejs rusza o&nbsp;10.00, ostatni z&nbsp;Ved Stranden wypływa między 16.00 a&nbsp;18.00, a&nbsp;do 3 stycznia odjazdy są tylko z&nbsp;przewodnikiem na żywo.</p>
<h3>Plan 2: dwa dni, centrum plus Kronborg i&nbsp;Frederiksborg (Discover 48&nbsp;h: 859&nbsp;DKK)</h3>
<table><thead><tr><th>Dzień</th><th>Pozycja</th><th>Cena w&nbsp;kasie, DKK (online)</th></tr></thead><tbody><tr><td>1</td><td>Rosenborg, Nationalmuseet, rejs Stromma, Tivoli</td><td>649 (610)</td></tr><tr><td>2</td><td>Kronborg (Helsingør)</td><td>150 (135)</td></tr><tr><td>2</td><td>Frederiksborg (Hillerød)</td><td>125</td></tr><tr><td>1–2</td><td>City Pass Large 48&nbsp;h (strefy 1–99)</td><td>320</td></tr><tr><td></td><td>Razem bez kart</td><td>1244 (1190)</td></tr><tr><td></td><td>Oszczędność z&nbsp;kartą</td><td>385 (331)</td></tr></tbody></table>
<p>Przy Frederiksborgu strona podaje tylko 125&nbsp;DKK, więc w&nbsp;kolumnie online liczymy tyle samo. Frederiksborg jest otwarty codziennie, także w&nbsp;poniedziałki, a&nbsp;Kronborg jest w&nbsp;poniedziałki zamknięty od listopada do końca marca (z&nbsp;wyjątkiem ferii zimowych), w&nbsp;pozostałe dni otwarty 10–16 (w&nbsp;weekendy listopada i&nbsp;grudnia do 17).</p>
<figure><img src="https://kastrup.cz/images/clanky/copenhagen-card/kronborg-1500.webp" alt="Zamek Kronborg w Helsingør z ceglanymi wałami obronnymi" loading="lazy"><figcaption>Kronborg w&nbsp;Helsingør, kwiecień 2026. Fot. <a href="https://commons.wikimedia.org/wiki/File:Kronborg_April_2026_08.jpg">ArildV</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>. Pomniejszone i przekonwertowane do formatu WebP.</figcaption></figure>
<p>Oba zamki w&nbsp;jeden dzień: między Hillerød a&nbsp;Helsingør jeździ lokalny pociąg Lille Nord (do 14 grudnia 2026 w&nbsp;ograniczonym rozkładzie), ale czas przejazdu sprawdź w&nbsp;rozkładzie, żeby wiedzieć, czy się zmieścisz. Traktuj ten plan jako rachunek, nie rozkład jazdy.</p>
<figure><img src="https://kastrup.cz/images/clanky/copenhagen-card/frederiksborg-1500.webp" alt="Zamek Frederiksborg w Hillerød nad jeziorem zamkowym" loading="lazy"><figcaption>Frederiksborg w&nbsp;Hillerød. Zdjęcie archiwalne, 2008. Fot. <a href="https://commons.wikimedia.org/wiki/File:Frederiksborg_Castle_and_boat_crop.jpg">Casper Moller from London, United Kingdom</a>, <a href="https://creativecommons.org/licenses/by/2.0">CC BY 2.0</a>. Pomniejszone i przekonwertowane do formatu WebP.</figcaption></figure>
<p>Spokojna wersja bez wypadu wygląda gorzej. Rosenborg, Nationalmuseet, Glyptotek, Tivoli i&nbsp;City Pass Small na 48 godzin (160&nbsp;DKK) dają 810&nbsp;DKK. Karta kosztuje 859, czyli jest o&nbsp;49&nbsp;DKK droższa, a&nbsp;z&nbsp;cenami online o&nbsp;89&nbsp;DKK.</p>
<h3>Plan 3: rodzina 2+2 (dzieci 5 i&nbsp;9 lat), trzy dni (Discover 72&nbsp;h)</h3>
<p>Karty: 2 × Discover 1039&nbsp;DKK + 2 × Kids 180&nbsp;DKK = 2438&nbsp;DKK.</p>
<table><thead><tr><th>Dzień</th><th>Pozycja</th><th>Dorośli</th><th>Dzieci</th><th>Razem</th></tr></thead><tbody><tr><td>1</td><td>Zoo (dziecko 3–14 lat: 160)</td><td>520</td><td>320</td><td>840</td></tr><tr><td>1</td><td>Tivoli (5-latek 100, 9-latek 200)</td><td>400</td><td>300</td><td>700</td></tr><tr><td>2</td><td>Rosenborg i&nbsp;Nationalmuseet (osoby poniżej 18 lat za darmo)</td><td>600</td><td>0</td><td>600</td></tr><tr><td>2</td><td>Rejs Stromma (dorośli 2 × 149)</td><td>298</td><td>x (cena dla 9-latka nieznana)</td><td>298 + x</td></tr><tr><td>3</td><td>Experimentarium (ceny online: ok. 230 i&nbsp;ok. 143, zależnie od dnia)</td><td>460</td><td>286</td><td>746</td></tr><tr><td>1–3</td><td>City Pass Small 72&nbsp;h (dzieci poniżej 12 lat z&nbsp;dorosłym za darmo)</td><td>440</td><td>0</td><td>440</td></tr><tr><td></td><td>Razem bez kart</td><td></td><td></td><td>3624 + x</td></tr><tr><td></td><td>Oszczędność z&nbsp;kartami</td><td></td><td></td><td>1186 + x</td></tr></tbody></table>
<p>Niewiadoma x to bilet na rejs dla dziewięciolatka. Stromma dawała 28 września pół ceny dzieciom 6–15 lat i&nbsp;rejs gratis dla dzieci do 5 lat, ale 7 października strona pokazywała już tylko cenę „od 16 lat”, więc kwoty nie podajemy. Jeśli trzeciego dnia wstawisz Kronborg i&nbsp;Frederiksborg zamiast Experimentarium (dorośli 550&nbsp;DKK, dzieci za darmo, choć Kronborg nie podaje granicy wieku; do tego dwa City Passy Large za 880&nbsp;DKK), wychodzi 3868 + x, czyli oszczędność 1430 + x.</p>
<p>Dziewięciolatek w&nbsp;Tivoli płaci jak dorosły: połowa ceny obowiązuje tylko do 7 lat. Dlatego w&nbsp;tym planie karty Kids się opłacają: wejścia dla dzieci do Zoo, Tivoli i&nbsp;Experimentarium to 906&nbsp;DKK, do tego rejs (x), a&nbsp;dwie karty Kids kosztują 360&nbsp;DKK. W&nbsp;planie z&nbsp;samych muzeów jest odwrotnie: dzieci i&nbsp;tak wchodzą za darmo, a&nbsp;do 12 lat jeżdżą z&nbsp;dorosłym bez biletu, więc dwie karty Kids za 100–260&nbsp;DKK każda to pieniądze wyrzucone w&nbsp;błoto. Pomysły, co jeszcze robić z&nbsp;dziećmi, znajdziesz w&nbsp;przewodniku <a href="/artykul/kopenhaga-z-dziecmi">Kopenhaga z&nbsp;dziećmi</a>; jest tam też krótszy przykład na jedną dobę w&nbsp;Zoo i&nbsp;Experimentarium.</p>
<h2>Copenhagen Card czy City Pass?</h2>
<p>City Pass to bilet komunikacji miejskiej (DOT), bez żadnych wstępów. Discover to w&nbsp;praktyce ta sama komunikacja co City Pass Large, plus wejścia. Porównanie sprowadza się więc do pytania, czy planowane wejścia kosztują więcej niż różnica w&nbsp;cenie.</p>
<p>Według <a href="https://dinoffentligetransport.dk/media/wlfdfnbo/dot-takstblad-2026-a.pdf">taryfy DOT na 2026 rok</a> City Pass Small (strefy 1–4, z&nbsp;lotniskiem) kosztuje dorosłego 100&nbsp;DKK za 24 godziny, 160 za 48 i&nbsp;220 za 72. City Pass Large (strefy 1–99, z&nbsp;Roskilde i&nbsp;Helsingør) kosztuje 200, 320 i&nbsp;440&nbsp;DKK. Do City Passu dorosły zabiera za darmo dwoje dzieci poniżej 12 lat, a&nbsp;młodzież 12–15 lat płaci połowę ceny.</p>
<p>Na dobę wychodzi tak: 589 minus 200 to 389&nbsp;DKK, które karta musi odrobić we wstępach, jeśli i&nbsp;tak bierzesz Large. W&nbsp;porównaniu z&nbsp;Small to 489&nbsp;DKK. Rosenborg, Nationalmuseet i&nbsp;Tivoli razem to 500&nbsp;DKK, więc ledwo pokrywają tę różnicę. Sam przejazd z&nbsp;lotniska Kastrup do centrum to trzy strefy i&nbsp;30&nbsp;DKK.</p>
<h2>Kiedy Copenhagen Card się nie opłaca?</h2>
<p>Kilka rzeczy, przez które rachunek rozjeżdża się najczęściej:</p>
<ul><li>Dzieci w&nbsp;muzeach. Osoby poniżej 18 lat wchodzą za darmo do Rosenborga (potrzebują jednak bezpłatnego biletu), Nationalmuseet, Glyptoteki (bilet tylko w&nbsp;kasie), Frederiksborga i&nbsp;Thorvaldsens Museum. Kronborg też wpuszcza dzieci za darmo, ale nie podaje, do ilu lat. Trzynastolatek z&nbsp;kartą Junior na dobę (399&nbsp;DKK) w&nbsp;dniu z&nbsp;Zoo i&nbsp;Tivoli oszczędza 11&nbsp;DKK: 160 + 200 + 50 za dziecięcy City Pass to 410. W&nbsp;dniu muzealnym zero.</li><li>Tivoli zamknięte między sezonami: od 2 do 12 listopada 2026, a&nbsp;po 3 stycznia 2027 do wiosny. Halloween trwa do 1 listopada, sezon świąteczny od 13 listopada do 3 stycznia, 24 grudnia park jest zamknięty.</li><li>Poniedziałki jesienią i&nbsp;zimą. Rosenborg od 2 listopada do 23 grudnia w&nbsp;poniedziałki jest zamknięty, Kronborg od listopada do końca marca (z&nbsp;wyjątkiem ferii zimowych), Nationalmuseet od listopada do marca (poza 7. tygodniem roku i&nbsp;Wielkanocą), Glyptotek i&nbsp;Thorvaldsens zawsze. Otwarte są m.in. Zoo, Frederiksborg, Stromma, Experimentarium, Planetarium i&nbsp;Tivoli w&nbsp;sezonie. Strona karty ma filtr „Open on Mondays” z&nbsp;31 miejscami.</li><li>Zegar od aktywacji. Karta aktywowana o&nbsp;14.00 działa do 13.59 następnego dnia, a&nbsp;od 2 listopada Rosenborg zamyka o&nbsp;16.00. W&nbsp;pierwszym dniu zostają Ci wtedy w&nbsp;Rosenborgu dwie godziny.</li><li>Zniżki online, których karta nie uwzględnia: Rosenborg 140 zamiast 150&nbsp;DKK, Nationalmuseet, Glyptotek i&nbsp;Kronborg po 135 zamiast 150, rejs z&nbsp;Ved Stranden w&nbsp;taryfie early bird 135&nbsp;DKK (rezerwacja co najmniej 3 dni wcześniej) zamiast 149 z&nbsp;Nyhavnu. Z&nbsp;nimi w&nbsp;planie 1 oszczędzasz 121 zamiast 160&nbsp;DKK. Karta nie ma też ceny studenckiej, a&nbsp;Rosenborg kosztuje studenta 100&nbsp;DKK, Glyptotek 120&nbsp;DKK.</li><li>Plan oparty na miejscach spoza listy, jak Den Blå Planet czy Rundetårn. Designmuseum Danmark karta obejmuje, ale sklepy z&nbsp;designem, takie jak HAY House czy Illums Bolighus, to już zakupy, nie wstęp (więcej w&nbsp;tekście o&nbsp;<a href="/artykul/dunski-design-kopenhaga">duńskim designie w&nbsp;Kopenhadze</a>). Każdy punkt planu sprawdź na liście atrakcji karty, zanim cokolwiek kupisz.</li><li>Kolejki. Karta ich nie skraca (wyjątek to Zoo, gdzie idziesz od razu do skanera), a&nbsp;do każdej atrakcji wejdziesz z&nbsp;kartą tylko raz. Inaczej jest w&nbsp;Tivoli: tego samego dnia wrócisz ze stemplem przy głównym wejściu.</li></ul>
<h2>Które muzea w&nbsp;Kopenhadze są za darmo?</h2>
<p>Zawsze za darmo jest Davids Samling (The David Collection, Kronprinsessegade 30–32), a&nbsp;dwa muzea z&nbsp;karty mają darmowe dni:</p>
<ul><li><a href="https://www.davidmus.dk/planlaeg-dit-besog">Davids Samling</a>: wstęp wolny do zbiorów i&nbsp;wystaw czasowych; w&nbsp;poniedziałki zamknięte, od wtorku do niedzieli 10–17, w&nbsp;środy do 21.</li><li><a href="https://www.thorvaldsensmuseum.dk/besoeg-museet">Thorvaldsens Museum</a>: za darmo w&nbsp;każdą środę, w&nbsp;pozostałe dni dorosły płaci 110&nbsp;DKK; w&nbsp;poniedziałki zamknięte.</li><li><a href="https://glyptoteket.com/visit/">Ny Carlsberg Glyptotek</a>: za darmo w&nbsp;ostatnią środę miesiąca, w&nbsp;pozostałe dni dorosły płaci 150&nbsp;DKK; w&nbsp;czwartki otwarte do 21, w&nbsp;poniedziałki zamknięte. Z&nbsp;kalendarza wychodzi, że najbliższe takie środy to 28 października i&nbsp;25 listopada 2026, ale muzeum samo dat nie podaje, więc potwierdź je na jego stronie.</li></ul>
<p>Nationalmuseet jest płatne dla dorosłych (150&nbsp;DKK, online 135), a&nbsp;darmowego dnia strona muzeum nie podaje. W&nbsp;darmowe środy karta niczego nie daje w&nbsp;Thorvaldsens i&nbsp;Glyptotece: płacisz za wstęp, który i&nbsp;tak jest wolny.</p>
<figure><img src="https://kastrup.cz/images/clanky/copenhagen-card/thorvaldsens-museum-1500.webp" alt="Kwadryga na dachu Thorvaldsens Museum w Kopenhadze" loading="lazy"><figcaption>Thorvaldsens Museum, w&nbsp;środy wstęp wolny. Zdjęcie z&nbsp;2017 roku. Fot. <a href="https://commons.wikimedia.org/wiki/File:Kopenhagen_(DK),_Thorvaldsens-Museum_--_2017_--_1482.jpg">Dietmar Rabich</a>, <a href="https://creativecommons.org/licenses/by-sa/4.0">CC BY-SA 4.0</a>. Pomniejszone i przekonwertowane do formatu WebP.</figcaption></figure>
<h2>Jak aktywować Copenhagen Card?</h2>
<p>Karta jest wyłącznie cyfrowa i&nbsp;działa w&nbsp;aplikacji „Copenhagen Card City Guide” (aplikacja ma też polską wersję). Kupujesz ją na stronie operatora i&nbsp;wpisujesz numer zamówienia w&nbsp;aplikacji albo kupujesz od razu w&nbsp;aplikacji. Zegar startuje przy aktywacji, więc kolejność ma znaczenie:</p>
<ol><li>Przed aktywacją ustaw w&nbsp;telefonie czas środkowoeuropejski, bo tak zaleca operator w&nbsp;FAQ. Internet jest potrzebny tylko do aktywacji, potem aplikacja działa offline. Zrzut ekranu karty nie wystarczy: atrakcje i&nbsp;kontrolerzy akceptują tylko aplikację.</li><li>Kliknij Activate w&nbsp;zakładce „My cards” i&nbsp;potwierdź przesunięciem (swipe). Czas liczy się od tego momentu, nie od pierwszego skanu, i&nbsp;sam go nie wstrzymasz ani nie cofniesz. Karta 24-godzinna aktywowana we wtorek o&nbsp;10.00 działa do środy 9.59. Jeśli aktywujesz kartę przez pomyłkę, napisz do obsługi z&nbsp;numerem zamówienia i&nbsp;karty.</li><li>Wszystkie karty z&nbsp;jednego zamówienia aktywują się naraz, więc aktywuj dopiero przed pierwszym wejściem, nie w&nbsp;hotelu.</li><li>Home of Carlsberg zarezerwujesz dopiero po aktywacji (numer karty widać tylko w&nbsp;aplikacji), więc zrób to zaraz po niej. Wieżę Vor Frelsers Kirke zarezerwuj z&nbsp;wyprzedzeniem. W&nbsp;Rosenborgu dostajesz na miejscu bilet z&nbsp;godziną wejścia. Rejs Stromma zarezerwujesz tylko osobiście w&nbsp;kasie przy Ved Stranden, a&nbsp;GoBoat tylko na miejscu.</li><li>Do atrakcji możesz wejść tuż przed końcem ważności karty i&nbsp;zostać w&nbsp;środku.</li></ol>
<p>Pełne zasady są na stronie <a href="https://copenhagencard.com/view/how-it-works">„jak to działa”</a>. Nieaktywowaną kartę możesz zwrócić z&nbsp;pełnym zwrotem pieniędzy w&nbsp;ciągu 6 miesięcy od zakupu, a&nbsp;jeśli jej nie aktywujesz, wygaśnie po 2 latach.</p>
<h2>Jak policzyć, czy karta opłaca się Tobie?</h2>
<p>Zanim klikniesz „kup”, wypisz atrakcje z&nbsp;planu razem z&nbsp;cenami kasowymi, dodaj City Pass na tyle godzin, ile ma karta, i&nbsp;od tej sumy odejmij cenę karty z&nbsp;tabeli. My przyjmujemy prostą granicę: przy oszczędności poniżej 100&nbsp;DKK nie warto wiązać się zegarem karty. Kup bilety osobno i&nbsp;online. Co jeszcze zobaczyć w&nbsp;mieście, podpowiadamy w&nbsp;<a href="/kopenhaga">przewodniku po Kopenhadze</a>.</p>
<h2>Często zadawane pytania</h2>
<h3>Czy dzieci mają Copenhagen Card za darmo?</h3>
<p>Nie. Dzieci 3–11 lat potrzebują karty Kids za 100–260&nbsp;DKK, najwyżej dwie na jedną kartę dorosłego i&nbsp;w&nbsp;tym samym zamówieniu. Dzieci poniżej 3 lat karty nie potrzebują.</p>
<h3>Czy Copenhagen Card obejmuje Tivoli?</h3>
<p>Wstęp tak, przejażdżki nie. Pamiętaj, że od 2 do 12 listopada 2026 park jest zamknięty.</p>
<h3>Czy z&nbsp;kartą dojadę z&nbsp;lotniska do centrum?</h3>
<p>Tak, ale tylko w&nbsp;wariancie Discover. Hop nie obejmuje komunikacji miejskiej ani dojazdu z&nbsp;lotniska.</p>
<p>Źródła: copenhagencard.com (cennik, FAQ, jak to działa, lista atrakcji), dinoffentligetransport.dk, publictransport.dk i&nbsp;dsb.dk (taryfa i&nbsp;City Pass), lokaltog.dk (pociąg Lille Nord), strony Rosenborga, Nationalmuseet, Glyptoteki, Thorvaldsens Museum, Davids Samling, Kronborga, Frederiksborga, Zoo, Tivoli, Stromma, Den Blå Planet, Rundetårn i&nbsp;Experimentarium. Ceny i&nbsp;godziny sprawdzone 7 października 2026 (ze stanu z&nbsp;28 września pochodzą tylko ceny Experimentarium i&nbsp;dziecięce bilety Stromma), przed zakupem zajrzyj jeszcze raz do cennika karty.</p>$k$, $k$Copenhagen Card 2026: ceny i czy się opłaca | Kastrup.pl$k$, $k$Ile kosztuje Copenhagen Card w 2026 i kiedy się opłaca? Ceny w DKK, co obejmuje, a czego nie, i trzy plany: 1 dzień, 2 dni z zamkami, rodzina 2+2.$k$, $k$copenhagen card$k$, 'cbf723ca-1307-4ffd-8717-5b673c8643cd', '415c2012-9d88-4267-9b21-63b93ab384ad', $k$https://kastrup.cz/images/clanky/copenhagen-card/rosenborg-jesien-1500.webp$k$, false)
on conflict (lang, slug) do update set title=excluded.title, perex=excluded.perex, content=excluded.content, meta_title=excluded.meta_title, meta_description=excluded.meta_description, focus_keyword=excluded.focus_keyword, image_url=excluded.image_url, updated_at=now()
returning id, slug, published;
